### ISSUE TITLE
Bug in  __overlap(self, interval_a, interval_b)

### ISSUE THREAD

**Issue by Jonas1312** [experiencor/basic-yolo-keras#1]
Line 35 in utils.py should be 
```
 return min(x2,x4) - x3
```
instead of 
```
 return min(x2,x4) - x1
```

**Comment by experiencor** [comment]
@Jonas1312 Thanks so much!

**Comment by Mirorrn** [comment]
hmm still have the feeling thats not coorect that's my implementation:
`    def iou(self, box):

        # determine the (x, y)-coordinates of the intersection rectangle
        dA =  min(self.w + self.x, box.w + box.x) - max(self.x, box.x)
        dB =  min(self.h + self.y, box.h + box.y) - max(self.y, box.y)
        # compute the area of intersection rectangle
        interArea = 0
        if (dA >= 0) and (dB >= 0):
            interArea = dA * dB

        # compute the area of both the prediction and ground-truth
        # rectangles
        boxAArea = (self.w) * (self.h)
        boxBArea = (box.w) * (box.h)

        # compute the intersection over union by taking the intersection
        # area and dividing it by the sum of prediction + ground-truth
        # areas - the interesection area
        return interArea / float(boxAArea + boxBArea - interArea)
`
