### ISSUE TITLE
Default Anchors

### ISSUE THREAD

**Issue by PabloLeon23** [experiencor/basic-yolo-keras#10]
Why do you choose that anchors? Must I change them if I use other dataset?

Thanks

**Comment by Mirorrn** [comment]
Probably yes. You can find the meaning of the anchors in the yolo9000 paper

**Comment by Mirorrn** [comment]
My question is here in what metric are the anchors, grid ?

**Comment by PabloLeon23** [comment]
Yes. For some reasons:

-  "pred_box_wh" is divided by grid sizes after use the anchors.
-  Don't make sense the sizes of the anchors in comparison with the input size.

**Comment by mrqorib** [comment]
@experiencor I'm sorry for asking it again. I've read the paper and actually I'm still in doubt about the anchor size. This is the figure in the paper: https://snag.gy/2RVq3i.jpg
Does the default anchors in your code is the [Pw1, Ph1, Pw2, Ph2, ..., Pw5, Ph5] in the diagram?

**Comment by experiencor** [comment]
@mrqorib Yes. That's true.

**Comment by mrqorib** [comment]
@experiencor Thank you for your answer Mr. Anh. I want to ask again, are the anchors dimension in actual image pixel, or after the image scaled to input size?

**Comment by experiencor** [comment]
The unit is the dimension of the cell. Says, an anchor with width 0.57273 means its width is 0.57273*cell_w. By proportions, it's the same before and after the scaling of input size.

**Comment by mrqorib** [comment]
@experiencor Thank you so much for your answer :)
Btw, it's a very great work. Thanks so much for sharing this repo to the world!

**Comment by SteveIb** [comment]
Hi,
[Pw1, Ph1, Pw2, Ph2, ..., Pw5, Ph5]
in case if I have 5 objects.
so if I have only 2 objects 
it should be four values something like [0.8223, 0.8223, 0.5882, 0.5882]
right?
