### ISSUE TITLE
Annotation Confusion

### ISSUE THREAD

**Issue by fakhouri-junior** [experiencor/basic-yolo-keras#102]
Hello
Thank you so much for your great work, I would like to ask you about annotations, I am extremely confused about them, it seems like there are 3 types of annotations voc, coco, and yolo. All are different: yolo requires the annotations to be in this form (x,y, w,h) however in voc (x_min, y_min, x_max, y_max)
How should I annotate my dataset?

Thank you so much

**Comment by experiencor** [comment]
@fakhouri-junior Please read the readme, section ```Usage for python code```.

**Comment by fakhouri-junior** [comment]
@experiencor I did actually, but the confusing part was about yolo's convention of using annotations (width and height). So I read the code you implemented and figured it out, there is a conversion in preprocessing.py file. It is clear now thank you so much for the help
