### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by ashah03** [experiencor/basic-yolo-keras#103]
The print statements are only compatible with python2 (i.e. they don't have parentheses). Is this something that could be fixed?

**Comment by friendmine** [comment]
print()

**Comment by experiencor** [comment]
@ashah03 Yes! This could be fixed easily. I will try to fix in the next few days.

**Comment by pchristian4481** [comment]
I am having problems with several of the programs with Python 3.6.  
gen_anchors.py - 
training.py
front_end.py

Has anyone successfully used 3.6 for this?

**Comment by HarkDev** [comment]
Working on it: https://github.com/HarkDev/basic-yolo-keras-py3

**Comment by TanFluent** [comment]
@HarkDev Have you finish your project on the py3 version of basic-yolo-keras ? I'm very interested on your work. But, it seems there is few update on it

**Comment by guysoft** [comment]
For reference, its fixed: https://github.com/experiencor/keras-yolo2/commit/6e11249a498da35ce5d6144d2330f66e435de411
