### ISSUE TITLE
Face detection

### ISSUE THREAD

**Issue by Aneesh-c4** [experiencor/basic-yolo-keras#112]
Can I use any available pre-trained weights for face detection? I could try C version of darknet and could run it
[https://github.com/dannyblueliu/YOLO-version-2-Face-detection](url)
. but How can I use this code to do the same?

**Comment by experiencor** [comment]
I provided the code to load darknet weight in the notebook ```Yolo Step-by-Step.ipynb```. You need to change the number of classes to suit your case.
