### ISSUE TITLE
Error when using pretrained weights full_yolo_backend.h5 

### ISSUE THREAD

**Issue by Wangduo428** [experiencor/basic-yolo-keras#113]
I downloaded the pretrained weights full_yolo_backend.h5  from the link you provided, and set it in the config.json, but when I trained it , an error  "You are trying to load a weight file containing 44 layers into a model with 2 layers."  came out. It seems like the it considered the backend of yolo as one layer... How to deal with this problem? Thanks.

**Comment by experiencor** [comment]
@Wangduo428 Please read section ```2. Edit the configuration file``` carefully. This weight is automatically loaded to the backend after model creation. It doesn't include the frontend layer. In your case, just leave the ```pretrained_weights``` empty.

**Comment by Wangduo428** [comment]
OK. Thanks very much! By the way, what dataset did you use to pretrain the backend of yolo? Imagenet?

**Comment by experiencor** [comment]
I trained on COCO2014 (http://cocodataset.org/#detections-challenge2017).

**Comment by PaParaZz1** [comment]
@Wangduo428  @experiencor  Could you tell me the details you solve the problem. I encountered the same problem and I leave "pretrained_weights" empty, but there is still the same errors. And should the frontend weights be trained on my own dataset?

**Comment by experiencor** [comment]
@PaParaZz1 still got this problem. Reading the readme carefully will be likely able to solve it.
