### ISSUE TITLE
Simple question on  object scale and no_object scale

### ISSUE THREAD

**Issue by Moondra** [experiencor/basic-yolo-keras#114]
Are these scaling the first element of the output vector, which determines if 
there is an object and there isn't an object? 

Thank you!

```
"object_scale":         5.0 ,           # determine how much to penalize wrong prediction of confidence of object predictors
  "no_object_scale":      1.0,            # determine how much to penalize wrong prediction of confidence of non-object predictors
```

**Comment by experiencor** [comment]
@Moondra The order in the output vector: x, y, w, h, confidence, classes. These parameters scale the penalty of confidence.

**Comment by Moondra** [comment]
Got it. Thank you.
