### ISSUE TITLE
what's the true_boxes means?

### ISSUE THREAD

**Issue by Comup-X** [experiencor/basic-yolo-keras#115]
what's the responsibility of the layer 
````
output = Lambda(lambda args: args[0])([output, true_boxes])
 ````

**Comment by experiencor** [comment]
This is just a hack to include true_boxes in the model, otherwise keras will throw an unconnected network error. true_boxes contain the list of object positions and sizes. It's redundant given y_batch provided by the batch_generator but it helps to reduce the complexity of tensorflow code.

**Comment by kervyRivas** [comment]
the value of true_box_buffer, is the maximum number of true boxes that an image can have?

**Comment by experiencor** [comment]
@kervyRivas Not a random value, of course. This number depends on your dataset and you should write a script to find out this number.

**Comment by Fenil3510** [comment]
@experiencor , could you explain in a little detail, what role would true_box_buffer(maximum ground_truth bounding boxes) play in the algorithm?
Thanks

**Comment by experiencor** [comment]
@Fenil3510 to limit the memory that holds bounding boxes' information passed to the GPU from CPU.
