### ISSUE TITLE
"tuple index out of range" running "gen_anchors.py"

### ISSUE THREAD

**Issue by ccasadei** [experiencor/basic-yolo-keras#118]
Hi.
Running the script "**gen_anchors.py**" I get the error "**tuple index out of range**" on line **79**.
I verified that by editing line **130** in "**annotation_dims.append ((relative_w, relative_h))**" (thus removing the "**map**") the script works correctly.

**Comment by ShwanMario** [comment]
@ccasadei 

I thought u can use list( map( ) ).

hope it would be helpful.

**Comment by ccasadei** [comment]
@ShwanMario 
Perfect!
Thank you!
