### ISSUE TITLE
how to Predict with GPU

### ISSUE THREAD

**Issue by LauryMiao** [experiencor/basic-yolo-keras#119]
Hi, I've trained with GPU, and now wanna predict using GPU.
Add these lines in frontend.py, but it didn't work. pls help
```python
import tensorflow as tf
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
config.gpu_options.allow_growth=True
set_session(tf.Session(config=config))
```

**Comment by experiencor** [comment]
@LauryMiao Having this line ```os.environ["CUDA_VISIBLE_DEVICES"] = "0"``` in predict.py is enought to make predictions using GPU.

**Comment by LauryMiao** [comment]
thanks, I've figured out the root cause: when using predict, a pure predict virtual environment has been created without tf-gpu(here), after install tf-gpu. works!

**Comment by anilkumarvvss** [comment]
@Paul0M  How exactly did you solve that issue? Can you please explain in detail? I already have tf-gpu installed.
