### ISSUE TITLE
not enough params

### ISSUE THREAD

**Issue by GiladAmar** [experiencor/basic-yolo-keras#12]
Block 14 of the notebook:
    train_imgs  = parse_annotation(coco_train_path) 

which uses parse_annotation from the python preprocessing.py script should be given a second param 'labels'.

```TypeError: parse_annotation() missing 1 required positional argument: 'labels'```

**Comment by experiencor** [comment]
@GiladAmar thanks! It's fixed.

**Comment by GiladAmar** [comment]
Thank you, that does the trick:-)
