### ISSUE TITLE
About the pixel of  image

### ISSUE THREAD

**Issue by hnsywangxin** [experiencor/basic-yolo-keras#120]
hello, now,I have a question, the size of input image  must be 416*416? My  picture is 2048*2048, because my project is to detection very small object(such as 28*28 in a large image),resize the picture to 416*416 will lead to poor results. thank you

**Comment by experiencor** [comment]
@hnsywangxin You use gen_anchors.py to generate the anchors. By this way, you never have to worry about the relative sizes of the objects w.r.t. the sizes of the images.
