### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by Yashesh9274** [experiencor/basic-yolo-keras#130]
python predict.py -c config.json -w /path/to/best_weights.h5 -i **/path/to/image/or/video**

In this command can we give more than one images for prediction at a time or folder of image??

because when i tried it gives error like :
![2error](https://user-images.githubusercontent.com/29895640/35091052-947f4d84-fc61-11e7-954a-18e5b725508e.png)

**Comment by experiencor** [comment]
@Yashesh9274 Yes. I have to specify an image or a video. It doesn't work with a folder of images. Would love if you can contribute.

**Comment by Yashesh9274** [comment]
@experiencor I have created a solution for that to access all the file of images folder..
and I have also added one thing that the output of the bounding boxed images will be stored in images/output folder so that the input and output images can be differentiated.

you just have to give input as ::

python predict.py -c config.json -w /path/to/best_weights.h5 -i /path/to/image/or/video (whole folder as an input)

![images_in_input](https://user-images.githubusercontent.com/29895640/35105852-b0bb102e-fc92-11e7-83ab-13cdd421363b.png)

and
output will be for every images [here i have done it for dummy data] : 
![output](https://user-images.githubusercontent.com/29895640/35105969-032d588a-fc93-11e7-938b-fcdf45ceb113.png)

**Comment by Yashesh9274** [comment]
Hello @experiencor ,
I have a question that how much time it takes to run 100 or 50 epochs?
and
which hardware is required for better performance in Full-YOLO?
..
Because I have a server with 12 cores of CPU and have no GPU with 32gb RAM and it is taking about 14:59:00 time for only 1 epoch of 95 steps after 3 warm up epochs so it is taking so long for a single epoch.
That's why, Please suggest something to make it faster.

Thank you for your help!

**Comment by experiencor** [comment]
It depends on the size of your dataset. I don't remember the number but using GPU is way faster than CPU as GPU has much more number of cores. I strongly suggest you to use some machine with GPU to speed up your experiments and learning.
