### ISSUE TITLE
INFINTE LOOP

### ISSUE THREAD

**Issue by kevinhoa95** [experiencor/basic-yolo-keras#132]
when I use gen_anchor.py to get the anchors number for my custom dataset, the iterator isn't stop! How can't I fix this.
Sorry, my English is not very good. Thanks!!

**Comment by experiencor** [comment]
@kevinhoa95 Can you provide the output?

**Comment by kevinhoa95** [comment]
This is the output. The 'dists' is not change!
iteration 3749: dists = 162.755397057
iteration 3750: dists = 162.755397057
iteration 3751: dists = 162.755397057
iteration 3752: dists = 162.755397057
iteration 3753: dists = 162.755397057
iteration 3754: dists = 162.755397057
iteration 3755: dists = 162.755397057
iteration 3756: dists = 162.755397057
iteration 3757: dists = 162.755397057
iteration 3758: dists = 162.755397057
iteration 3759: dists = 162.755397057
.....

**Comment by experiencor** [comment]
@kevinhoa95 This happens occasionally with KMean. I think that you will succeed after running it a few times. It'd be very strange or something peculiar about your dataset that it fails all the time.

**Comment by kevinhoa95** [comment]
It was running after I added some new data to the dataset.
Thank you so much!
