### ISSUE TITLE
Question about gen_anchors.py

### ISSUE THREAD

**Issue by szm2015** [experiencor/basic-yolo-keras#133]
Hi, I'm trying to rewrite your code for generating anchors for my custom data but I have a question!
At line 124 and 125 of the code, you first scale the object's width and height by cell_w and cell_h which are computed as follows:
`cell_w = image['width']/grid_w`
`cell_h = image['height']/grid_h`
 Then the k-means algorithm is applied. Shouldn't the object's width and height be scaled by 32 as it's  YOLO network's downsampling factor? Of course it's obvious that if the image['width'] and image['height'] are the same as config['model']['input_size'] the scaling factor will still be 32. I just wonder why it should be different for other image sizes.
Thank you

**Comment by experiencor** [comment]
Hi @szm2015, the sizes of the objects are relative to cell sizes in YOLO. So I cluster using their relative sizes. 

Other than that, different input sizes divide the image into different numbers of cells. 416x416 input => 13x13 grid. 320x320 input => 10x10 grid. The size of the cell depends on the grid size.

**Comment by experiencor** [comment]
Hi @szm2015 You are right that the size of the cells of the NORMALIZED input image (size config['model']['input_size'] X config['model']['input_size']) is fixed at 32pi X 32pi.

But the size of the cells of the ORIGINAL input image depends on the size of the original image. image['width'] and image['height'] are the original image sizes, not the normalized sized config['model']['input_size']. So I cluster the relative sizes of the objects, which are ORIGINAL object sizes over ORIGINAL cell sizes.
