### ISSUE TITLE
preprocessing issue

### ISSUE THREAD

**Issue by jfizzle** [experiencor/basic-yolo-keras#134]
I'm having an issue running gen_anchors.py on the raccoon dataset as well as train.py on a new dataset:

I get this error:
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

after I specify the absolute path to the annotation folder in config (prior to that, it says it can't find the annotation folder). 

I would think this means my annotations are bad xml for my new dataset, but since this is happening to the raccoon dataset, it seems like it could be something else.

**Comment by jfizzle** [comment]
figured it out ... I've been trying to get this to work with FloydHub ... Floydhub puts a hidden file in the directory, so I had to put this in preprocessing.py to get it to ignore the hidden file:

def listdir_nohidden(path):
    for f in os.listdir(path):
        if not f.startswith('.'):
            yield f

def parse_annotation(ann_dir, img_dir, labels=[]):
    all_imgs = []
    seen_labels = {}
    
    for ann in sorted(listdir_nohidden(ann_dir)):
        img = {'object':[]}
        
        tree = ET.parse(ann_dir + ann)

**Comment by geschaftsreise** [comment]
I'm having the same error. Part of my problem is that there isn't a whole lot of documentation about what things should look like at all of these steps if something doesn't go right.
For example when I download and unzip the annotations data, there are six file (not two separate 'train' and 'val' folders as the code indicates), so I seperated the three 'captions' 'instances' and 'person' json files into the respective train and val folders. And I'm assuming that's how it's meant to be set up but there's no elucidation of that setup step anywhere.
