### ISSUE TITLE
web demo error

### ISSUE THREAD

**Issue by ldenoue** [experiencor/basic-yolo-keras#137]
![image](https://user-images.githubusercontent.com/149561/35539731-a9e81706-0507-11e8-92b0-cb79d574191c.png)

**Comment by experiencor** [comment]
@ldenoue Have you resolved this? It only works in Linux btw.

**Comment by ldenoue** [comment]
No because I’m on Mac.
But it being browser based, why does it only run on Linux?
What can I modify to make it run elsewhere?

**Comment by experiencor** [comment]
It highly depends on the browser (specifically, the WebGL implementation of that browser) so I don't have any other advice than debugging the errors one by one.

In my case, I tested it on Chrome, Ubuntu 16.04.
