### ISSUE TITLE
error loading weights

### ISSUE THREAD

**Issue by simapero** [experiencor/basic-yolo-keras#144]
Hi, I was trying to run train.py
This is my configuration file:
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "/home/magnus/Members/Laura/Instruments_YOLO/raccoon_dataset-master/images/",
        "train_annot_folder":   "/home/magnus/Members/Laura/Instruments_YOLO/raccoon_dataset-master/anns/",     
          
        "train_times":          10,
        "pretrained_weights":   "full_yolo_backend.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_raccoon.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}
I didn't change anything in your code but when I run it I get a net with a wrong amount of layers and I don't understand why.
Here's the error:
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
input_1 (InputLayer)             (None, 416, 416, 3)   0                                            
____________________________________________________________________________________________________
model_1 (Model)                  (None, 13, 13, 1024)  50547936    input_1[0][0]                    
____________________________________________________________________________________________________
conv_23 (Conv2D)                 (None, 13, 13, 30)    30750       model_1[1][0]                    
____________________________________________________________________________________________________
reshape_1 (Reshape)              (None, 13, 13, 5, 6)  0           conv_23[0][0]                    
____________________________________________________________________________________________________
input_2 (InputLayer)             (None, 1, 1, 1, 10, 4 0                                            
____________________________________________________________________________________________________
lambda_2 (Lambda)                (None, 13, 13, 5, 6)  0           reshape_1[0][0]                  
                                                                   input_2[0][0]                    
====================================================================================================
Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672
____________________________________________________________________________________________________
Loading pre-trained weights in full_yolo_backend.h5
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    _main_(args)
  File "train.py", line 120, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/home/magnus/Members/Laura/Instruments_YOLO/raccoon_dataset-master/frontend.py", line 239, in load_weights
    self.model.load_weights(weight_path)
  File "/home/magnus/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2619, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/magnus/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 3068, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 44 layers into a model with 2 layers.

**Comment by experiencor** [comment]
@simapero It should be ""pretrained_weights":   "full_yolo_raccoon.h5". Please read section ```2. Edit the configuration file``` carefully.

**Comment by simapero** [comment]
solved! Thanks
