### ISSUE TITLE
Get DOI

### ISSUE THREAD

**Issue by thorstenwagner** [experiencor/basic-yolo-keras#145]
Hi,

I would like to cite your implementation / repository in a current research paper. It would be really helpfull if you would register a DOI number for your repo using https://zenodo.org .

Would that be possible?

Best,
Thorsten

**Comment by experiencor** [comment]
Hi @thorstenwagner This is the DOI of the release/: https://zenodo.org/badge/latestdoi/85842387

**Comment by thorstenwagner** [comment]
Thank you very much! You might also put the DOI badge into your readme. It always updated if you release a new version.

Best,
Thorstem
