### ISSUE TITLE
true_boxes value?

### ISSUE THREAD

**Issue by shahlearner** [experiencor/basic-yolo-keras#147]
I am trying to do training on my custom data with 2-3 classe.. How the buffer value is set to value 50, specifically how should I change this to adapt to my dataset.

**Comment by experiencor** [comment]
@shahlearner yes. It's the max number of box in all images.

**Comment by voqtuyen** [comment]
This means that we can only predict totally 50 objects in a given image, if there are more than 50, the algorithm will fail to predict the remaining other than 50 objects with highest confidence? Thanks

**Comment by experiencor** [comment]
@voqtuyen It only affects the training process in which only that many labels are fed to the network. But there's no such limit during predictions.
