### ISSUE TITLE
Jupyter Step-by-Step

### ISSUE THREAD

**Issue by titanbender** [experiencor/basic-yolo-keras#150]
Hi Experiencor, 

Thanks for making this great code available! 

I've been trying to run the Notebook guide, but I'm stuck with loading the pre-trained weights. 
As mentioned, I've downloaded the different weights from the different architectures and tried to load them in the guide. However, I get the following error message with every model:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-0e0bea352cf6> in <module>()
     20         bias   = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[1].shape))
     21         kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
---> 22         kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
     23         kernel = kernel.transpose([2,3,1,0])
     24         conv_layer.set_weights([kernel, bias])

ValueError: cannot reshape array of size 41237 into shape (425,1024,1,1)`

Do you know where I'm going wrong here? 

Thanks in advance,
Johan

**Comment by JacoGasp** [comment]
Hey @titanbender,

I'm facing the same problem. Did you solve it?
