### ISSUE TITLE
Expanding Annotations from Jupyter Step-by-Step

### ISSUE THREAD

**Issue by titanbender** [experiencor/basic-yolo-keras#151]
Hi Experiencor - 

Thanks for sharing your work with all of us. I'm trying to run the Jupyter Notebook guide, but I'm having issues with converting the COCO Annoations to VOC Pascal. When I open the zip folder that you've mentioned in your guide and expand to JSON file is empty - even though it still takes up multiple hundreds of MB. I also cannot detect any keys in the file and hence cannot convert it to VOC. Am I missing something? 

Link to the annotations - http://images.cocodataset.org/annotations/annotations_trainval2014.zip

**Comment by experiencor** [comment]
@titanbender still got this problem?
