### ISSUE TITLE
How to make sure that the grid level annotation is correct

### ISSUE THREAD

**Issue by AshStuff** [experiencor/basic-yolo-keras#152]
I am trying to train on my custom dataset. I have a question on the grid level annotation. I want to make sure that  after converting the Annotation which follows pascal voc dataset to YOLO Annotation grid level format. Is there a Visualization method to view it ?

**Comment by experiencor** [comment]
@AshStuff I don't know of any tool like that. I recommend you to note jupyter notebook for this.
