### ISSUE TITLE
True_box_buffer

### ISSUE THREAD

**Issue by groot-1313** [experiencor/basic-yolo-keras#153]
What is the significance of true_box_buffer, and how do you go about setting it?

**Comment by experiencor** [comment]
@groot-1313 It's the max number of bounding boxes in all images.

**Comment by Fenil3510** [comment]
@experiencor , you mean per image , right?
Then what about the BOX variable?
as in the below one


`LABELSLABELS  ==  [['RBC''RBC']]

  IMAGE_HIMAGE_H, IMAGE_W = 416, 416
GRID_H,  GRID_W  = 13 , 13
BOX              = 5
CLASS            = len(LABELS)
CLASS_WEIGHTS    = np.ones(CLASS, dtype='float32')
OBJ_THRESHOLD    = 0.3
NMS_THRESHOLD    = 0.3
ANCHORS          = [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828]

NO_OBJECT_SCALE  = 1.0
OBJECT_SCALE     = 5.0
COORD_SCALE      = 1.0
CLASS_SCALE      = 1.0

BATCH_SIZE       = 16
WARM_UP_BATCHES  = 100
TRUE_BOX_BUFFER  = 50`
