### ISSUE TITLE
Training a multiclass detector

### ISSUE THREAD

**Issue by IcyFrequency** [experiencor/basic-yolo-keras#156]
Hi,

Im using this code with a custom dataset, where i have images of three different classes separately (each image contains only one class). The labels is set as follows:
`labels: ["class1", "class2", "class3"]`
When predicting, the model did not predict any of the three classes. However, when I tried training with labels set to one class, the model managed to predict objects of that trained class. 

I assume that when I was training a model with all the labels, only images containing all three classes are fed to the network, which in my case is 0.

How should I go about doing this? Have I missed something important?

I appreciate all the help I can get :)

P.S: @experiencor Great code, really nice to work with!

**Edit**
SOLVED:
1) Took 1 image from each class (3 classes) and combined the three images into 1 image.
2) Annotated the image.
3) Trained a model with labels set to three classes.

This solved my issue; hope it might help someone.

**Comment by anvenkat09** [comment]
Hi @IcyFrequency,

I'm actually having similar problems. Could you tell me what you mean by combining an image from each class into one image? I assume that if I wanted to do multiclass, all my images would have to have objects from all the classes?

**Comment by IcyFrequency** [comment]
Hi @anvenkat09 

If you have two images of two separate classes, meaning image1.jpg contains class1 and image2.jpg contains class2, you want to merge image1.jpg and image2.jpg into image3.jpg now containing both class1 and class2.

This code is what I used for the image merging phase:
https://stackoverflow.com/questions/30227466/combine-several-images-horizontally-with-python

Once you have the merged image3.jpg you need to annotate it and use as apart of your trainingset.

Hope this helps!
