### ISSUE TITLE
(Potential Error in)  parse annotation function in preprocessing.py

### ISSUE THREAD

**Issue by VamshikShetty** [experiencor/basic-yolo-keras#159]
In line 39 of preprocessing.py
len(labels) > 0 ( where lables is the list of all the classes ) will return true when there are lables in list hence doing opposite of what is required it should be len(labels) == 0 
```
                        if len(labels) > 0 and obj['name'] not in labels:
                            break
                        else:
                            img['object'] += [obj
```

Please correct me if im wrong , thanks inadvance

**Comment by experiencor** [comment]
@VamshikShetty yes, it is but what's your point?

**Comment by VamshikShetty** [comment]
Anyway its is very trivial thing and nothing big to be discuss about but given you have written such neat code thought i would just mention it.

if labels = ['RBC', 'Raccon', 'Kangaroo'] 
then len(label)  is 3 and if we come across obj['name'] as 'Car' then IF Condition is true and it will break from the loop saving unnecessary computation.

But if we pass empty list ( I know empty list scenario doesnt make any sense here)  then len(label) is 0 given AND logic  IF condition will always remain false
so unrequired computation will happen but whats the point of len(labels) then why dont you have IF condition has:
```
if obj['name'] not in labels:
    break
```

what you want is  
```
if len(labels)==0 or obj j['name'] not in labels:
```
Anyway just a silly thing.... Beautiful code by the way

**Comment by experiencor** [comment]
@VamshikShetty interesting note! But when ```labels``` is empty, I still want it to do detection on all the labels encountered in the dataset. This is useful in the case that I may not know what labels are there in the dataset.

If I specify some classes in ```labels```, it will restrict to doing detection on these classes only.
