### ISSUE TITLE
train with TF 1.0 CUDA 8.0 BackEnd

### ISSUE THREAD

**Issue by zeynali** [experiencor/basic-yolo-keras#161]
Hi,
My Tensorflow BackEnd version is 1.0 , is this possible worked for my system? can be trained Full YOLO with GTX 1080 8G , RAM 16G , CPU i3 7100k?
please mention your cuda/cudnn version that your are tested. 
and i want to calculate mAP and see losses for training and validation at the same time , is this possible ?

OS : ubuntu 16.04

**Comment by experiencor** [comment]
@zeynali GTX1080 is perfectly fine. You may possibly install the right version of Tensorflow (1.3), Keras (2.0.8), and cuda (8.0).

**Comment by zeynali** [comment]
Hi ,
it isn't possible with one 1080(8G) , when i ran .ipynp i got OOM error : 
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

**Comment by experiencor** [comment]
@zeynali The batch_size is too big. You need to use a smaller batch_size.
