### ISSUE TITLE
train times  vs nb_epochs

### ISSUE THREAD

**Issue by Moondra** [experiencor/basic-yolo-keras#168]
What is the difference between "train_times" and "nb_epochs"?

Each epoch, should be one pass through the training_data set, but we have two different parameters for this.

Thank you.

**Comment by LucasVandroux** [comment]
`nb_epochs` is the maximum number of epochs used during the training (the training might stop earlier if `val_loss` is not improving for 3 consecutive epochs) while `train_times` is the number of time the full dataset is going to be feed to the network during one epoch. If you have a normal size dataset, it is better to keep it at 1.

I kept `train_times = 10` with a large dataset when I started using this code and I overfit my dataset: #157
