### ISSUE TITLE
Fps : keras yolo vs official darknet yolo

### ISSUE THREAD

**Issue by qjadud1994** [experiencor/basic-yolo-keras#171]
There is a question about the speed of the yolo model.

The official YOLO v2 has an Fps of 40 to 67 and a Tiny YOLO of 207 fps.
(https://pjreddie.com/darknet/yolo/)

However, with the Keras, the YOLO v2 is measured at 9 fps and the Tiny YOLO at 12 fps based on the GTX-1080.

Why are there so many differences in speed?

**Comment by experiencor** [comment]
@qjadud1994 The reason may be that my prediction code is not optimized and coded in python. The published result is in C and I think that it contains many performance hacks.
