### ISSUE TITLE
some question about your system

### ISSUE THREAD

**Issue by zeynali** [experiencor/basic-yolo-keras#175]
Q1) Please more detailed what's you cuda/cudnn/Tensorflow version that you are tested? and you GPU? is this possible with TF 1.0 BackEnd?
Q2) These scripts read jpg / xml files directly from foldes? Should be needed to drop up we own jpg/xml into your folders?

```
    train_image_folder <= the folder that contains the train images.

    train_annot_folder <= the folder that contains the train annotations in VOC format.

    valid_image_folder <= the folder that contains the validation images.

    valid_annot_folder <= the folder that contains the validation annotations in VOC format.
```

**Comment by experiencor** [comment]
@zeynali 

Q1) Sorry for not being clear in the readme. Cuda 8.0; Tensorflow 1.3; GPU K80. I ran it just fine on Tensorflow 1.0. Need 1.3 for ongoing multi-GPU code.

Q2) Yes. The jpg/xml should be organized in this manner.
