### ISSUE TITLE
Clarification on purpose of the two sets of weights

### ISSUE THREAD

**Issue by tlkh** [experiencor/basic-yolo-keras#176]
I think it's worth expanding a bit on this, and I'm not sure if I understand enough to write it myself and do a pull request.

If I understand everything correctly, the backend weights .h5 file is only needed during model creation, and not for inference. During inference (predict.py) only the final, trained weights are used. 

Hence if we need to load the model into another framework (e.g. CoreML or Movidius NCS SDK) we just load the final, trained .h5 file.

Is my understanding correct?

Original segment in README.md:

> Download pretrained weights for backend (tiny yolo, full yolo, squeezenet, mobilenet, and inceptionV3) at:
> https://1drv.ms/f/s!ApLdDEW3ut5fec2OzK4S4RpT-SU
> These weights must be put in the root folder of the repository. They are the pretrained weights for the backend only and will be loaded during model creation. The code does not work without these weights.
> The link to the pretrained weights for the whole model (both frontend and backend) of the raccoon detector can be downloaded at:
> https://1drv.ms/f/s!ApLdDEW3ut5feoZAEUwmSMYdPlY
> These weights can be used as the pretrained weights for any one class object detectors

**Comment by experiencor** [comment]
@tlkh Yes, you are right. You just need to load the final trained .h5 file when doing prediction. This file contains both backend and frontend weights, while the backend weights .h5 only contains the weight of the backend.
