### ISSUE TITLE
File

### ISSUE THREAD

**Issue by Sayantan17** [experiencor/basic-yolo-keras#177]
hello @experiencor Where should i divide the folder into 4 parts 
I m using Anaconda , through it i use jupyter notebook so in which directory I should divide in utils? 

& train_image_folder <= the folder that contains the train images.
train_annot_folder <= the folder that contains the train annotations in VOC format.
valid_image_folder <= the folder that contains the validation images.
valid_annot_folder <= the folder that contains the validation annotations in VOC format

Of COCO dataset which you provided I would put some images in the 2 folders & their XML file in another 2 
So where should I make these 4 folders ? Which will be my root directory?

Also where to put tiny-yolo_backend.h5 weight file as i directly use jupyter? I m asking in which directory?

**Comment by experiencor** [comment]
Hi @Sayantan17. You should put tiny-yolo-racoon.h5 in the root folder (the one which contains frontend.py, backend.py, ...).

The locations of these image and xml folder don't matter, but they should be specified in the config file config.json.

**Comment by Sayantan17** [comment]
@experiencor  THANKS it means where i downloaded (cloned the repository contents i should keep all the materials including these 4 folders including the .json file there & consequently making changes by  directory of the files by  making changes here 
 },

    "train": {
        **"train_image_folder":   "/home/andy/github/raccoon_dataset/images/",
        "train_annot_folder":   "/home/andy/github/raccoon_dataset/annotations/",**     
          
        "train_times":          10,
        "pretrained_weights":   "full_yolo_raccoon.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_raccoon.h5",
        "debug":                true
    },

right? just the cloned filed directory will come here to be replaced by the highlighted portion?
Thanking you.

**Comment by Sayantan17** [comment]
@experiencor Thanks i will check i will add Comment if there is any problem.

**Comment by experiencor** [comment]
@Sayantan17 I think that the code in coco2pascal.py will convert all 83k images. You need to modify this code if you want to shrink the dataset.
