### ISSUE TITLE
ValueError: You are trying to load a weight file containing 44 layers into a model with 2 layers.

### ISSUE THREAD

**Issue by zeynali** [experiencor/basic-yolo-keras#178]
Hi,
when i ran python train.py -c config.json i get above error.
My GPU 1080 , ubuntu 16.04 , keras 2.1.5 , TF 1.5 , CUDA 9 , CUDNN 7

i also downloaded full_yolo_backend.h5 and replace with full_yolo_raccon.h5 in "pretrained_weights":  at config.json
what do i do ?

**Comment by Sayantan17** [comment]
Buddy use anaconda rather than the python script. This will generally avoid the error.

**Comment by experiencor** [comment]
@zeynali You are loading the wrong weight file. Please read section ```2. Edit the configuration file``` carefully.

**Comment by zeynali** [comment]
Hi , i followed your command that mentions. 
Now i have `mobilenet_backend.h5` and i want to fine-tune on VOC 2007 .
that is my config.json:

```
{
    "model" : {
        "architecture":         "MobileNet",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog","horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

    },

    "train": {
        "train_image_folder":   "/home/mm/Detection-keras/basic-yolo-keras/VOCdevkit/VOC2007/JPEGImages/",
        "train_annot_folder":   "/home/mm/Detection-keras/basic-yolo-keras/VOCdevkit/VOC2007/Annotations/",     
          
        "train_times":          10,
        "pretrained_weights":   "mobilenet_backend.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        0,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "mobile_yolo_voc7.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "/home/mm/Detection-keras/basic-yolo-keras/VOCdevkit/VOC2007/JPEGImages/",
        "valid_annot_folder":   "/home/mm/Detection-keras/basic-yolo-keras/VOCdevkit/VOC2007/Annotations/",

        "valid_times":          1
    }
}

when i run python train.py -c config.json i get this error : 

```
python train.py -c config.json
Using TensorFlow backend.
Seen labels:	{'bicycle': 807, 'pottedplant': 1217, 'tvmonitor': 728, 'chair': 2806, 'boat': 791, 'sheep': 664, 'horse': 801, 'motorbike': 759, 'bird': 1175, 'head': 880, 'aeroplane': 642, 'bus': 526, 'hand': 1380, 'train': 630, 'foot': 806, 'diningtable': 609, 'cow': 685, 'car': 3185, 'dog': 1068, 'cat': 759, 'person': 10674, 'bottle': 1291, 'sofa': 821}
Given labels:	[u'aeroplane', u'bicycle', u'bird', u'boat', u'bottle', u'bus', u'car', u'cat', u'chair', u'cow', u'diningtable', u'dog', u'horse', u'motorbike', u'person', u'pottedplant', u'sheep', u'sofa', u'train', u'tvmonitor']
Overlap labels:	set([u'sheep', u'horse', u'bicycle', u'bottle', u'cow', u'sofa', u'motorbike', u'dog', u'cat', u'person', u'train', u'boat', u'aeroplane', u'bus', u'pottedplant', u'tvmonitor', u'chair', u'bird', u'diningtable', u'car'])
2018-03-11 18:42:21.933670: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-11 18:42:22.025154: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-11 18:42:22.025430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.835
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.50GiB
2018-03-11 18:42:22.025444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
(13, 13)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0                                            
__________________________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 3228864     input_1[0][0]                    
__________________________________________________________________________________________________
conv_23 (Conv2D)                (None, 13, 13, 125)  128125      model_1[1][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 5, 25 0           conv_23[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 10,  0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 13, 13, 5, 25 0           reshape_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 3,356,989
Trainable params: 3,335,101
Non-trainable params: 21,888
__________________________________________________________________________________________________
Loading pre-trained weights in mobilenet_backend.h5
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    _main_(args)
  File "train.py", line 120, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/home/mm/Detection-keras/basic-yolo-keras/frontend.py", line 239, in load_weights
    self.model.load_weights(weight_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 3354, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 54 layers into a model with 2 layers.

```

**Comment by zeynali** [comment]
Now i trained scratch without pretrained model , it seem work . 
Q1)why don't worked with pretrained model ? 
Q2) when i don't used pretrained model , in this case , the model train from scratch even feature extractor layers ? if so , that's not good work.
Q3) when the model start to training , the current recall was not zero but after some of iteration this value go to fix zero and but average recall isn't zero , ٰThat's because initial values of current recall was not zero because of this isn't go to zeros.

[http://uupload.ir/files/h3s_screenshot_from_2018-03-11_19-28-44.png](url)

**Comment by experiencor** [comment]
@zeynali You still load the wrong file. ```mobilenet_backend.h5``` is not supposed to be used the pretrained weight for the whole model. Please read Section 2 of readme carefully. The LONG readme will help you clear all the doubts above.

10 values are the w and h of the 5 bounding boxes: w1, h1, ..., w5, h5.

**Comment by zeynali** [comment]
@experiencor , Hi Dear , I read the full section 2 . but i want you one things , you are assume that you want to train raccoon with full yolo and want to use fine-tuning , so please link me the pretraind model to put the config. 

```
1- please put your system and versions of cuda/cudnn and GPU / Ram , .... that you've tested.
2- We always remember when we want to spend time on something, or to step by step, with the possibility of mentioning it, or to make a complete remark, and assume that all the audiences are primitive.
```

**Comment by experiencor** [comment]
@zeynali 

Q1) I find no reason that GTX1080 could not be used to train as long as you set the right batch_size. Too large of a batch size would crash the GPU.

Q2) Mobilenet is the best among those, but FullYolo is the best overall.

**Comment by legnaib** [comment]
I had the same problem. Following helps to solve it (if you used keras-yolo2):

Go to frontend.py (in the same directory as train.py) to the function self.load_weights (around line 250). There it says self.model.load_weights(weight_path), but this is wrong. You must change it to self.model.layers[1].load_weights(weight_path)

The first command will load the weights to the whole model, but this can't work. The model looks like the following: Input layer -> "Model" layer -> some other layers -> output. (With self.model.summary() and self.model.layers[1].summary() you can see the structure of your model)

The pretrained weights must be loaded in the "model" layer (This is layer[1]) and NOT to the whole model.

After this change, everything worked fine for me.
I hope I can help you (maybe a little bit late), but I had this issue a long time and can't solve it!

**Comment by imranparuk** [comment]
Could the author validate that @legnaib solution is sensible. The fix works for me, just want to confirm that it fits in with the whole system.

**Comment by rodrigo2019** [comment]
I think there is a missunderstanding here, the pretrained weights in json file, it is a WHOLE model trained previously. The pre trained weights to the BACKEND model will be always loaded, you just need leave the model in the root directory. If you you change as @legnaib said, you can't load the model in the future to keep training or to do inferences, because you changed the function in the way that is just possible to load the backend weights and not the whole model.
The function load_weights in this [line](https://github.com/experiencor/keras-yolo2/blob/master/frontend.py#L242) it is used [here](https://github.com/experiencor/keras-yolo2/blob/master/train.py#L78) loading the model from json file, the backend is loaded [here](https://github.com/experiencor/keras-yolo2/blob/master/backend.py#L167) which the name is a constant, so if you dont have this weights or changed the name, you will get a error.

If you want to train a model with a fresh backend, you can put `try:/except:` avoiding the error when the backend try to load the weights,

**Comment by manjeet87** [comment]
@rodrigo2019  is correct and clarified the situation, actually the word 'pretrained weight' used both for backend model and whole model, created a confusion. Request @experiencor to update the references for both in readme and .config file... to avoid confusion.  Anyway thanks for the wonderful work!

**Comment by legnaib** [comment]
Yes @rodrigo2019 I saw this point two. So I add the argument backend to the load_weights function and with and if clause I get both cases to load the initial backend (with backend = True) and to load generated whole models (with backend = False)

Or you change it for the first time you initialize your backend and then you're switching back to normal code to load the weights from your previously trained whole models
