### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by Rahul9650** [experiencor/basic-yolo-keras#181]
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
    
    },
    
    "train": {
        "train_image_folder":   "F:/downloads",
        "train_annot_folder":   "F:/downloads",      
        
        "train_times":          10,
        "pretrained_weights":   "full_yolo_backend.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        3,
        
        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,
        "saved_weights_name":   "full_yolo_backend.h5",
        "debug":                true
    },
    
    "valid": {
        "valid_image_folder":   "F:/downloads",
        "valid_annot_folder":   "F:/downloads",
        
        "valid_times":          1
    }
}
Traceback (most recent call last):

  File "<ipython-input-21-78ed440e387c>", line 27, in <module>
    "debug":                true

NameError: name 'true' is not defined 

@experiencor  Hello can you guide how to  solve the given issue as i have all the files including the config.json file & i've made the necessary changes & tried importing  the **full_yolo_backend.h5** file & error is the the traceback attached above.

**Comment by experiencor** [comment]
Hi @Rahul9650! Please read the readme carefully, especially Section 2. It will help you avoid a lot of errors. Specifically, you should not try to load full_yolo_backend.h5.
