### ISSUE TITLE
Pretrain image classifier

### ISSUE THREAD

**Issue by RichardSieg** [experiencor/basic-yolo-keras#182]
Hey! If I understood it correctly, your implementation of the model basically consist of two steps. First, a classical image classifier is created by e.g. `FullYoloFeature` and then the detection layer is put on top of it via
```
output = Conv2D(self.nb_box * (4 + 1 + self.nb_class),
                        (1,1), strides=(1,1),
                        padding='same',
                        name='conv_23',
                        kernel_initializer='lecun_normal')(features)
output = Reshape((self.grid_h, self.grid_w, self.nb_box, 4 + 1 + self.nb_class))(output)
output = Lambda(lambda args: args[0])([output, self.true_boxes])
```
We apply YOLO to find certain regions on documents, so our idea is to pretrain the classifier on document data. Is it correct that we would just need to create one of the features and train it on our data?

Thanks!

Richard

**Comment by experiencor** [comment]
Hi @RichardSieg! You are right that the model has 2 parts: feature extraction part (backend) and detection part (frontend).

You can straight away train the whole model using the provided backend weights to do detection on documents, no need to pretrain the classifier.

**Comment by RichardSieg** [comment]
Yes, this is what we did so far and it is already performing really well (that's why we choose your model). We just had the idea to retrain the underlying classifier (i.e. "extending" the full yolo weights) with document datasets, such that the model is already "used to" document data before starting detection. But we also found nice datasets (Tobacco etc...) with box detection and will run these first before learning our specific task.

**Comment by RichardSieg** [comment]
BTW what I did is:
```
def create_classifier(input_size,
                      nb_classes=15,
                      ):
    input_image = Input(shape=(input_size, input_size, 3))
    yolo_backend = FullYoloFeature(input_size)
    features = yolo_backend.extract(input_image)
    x = GlobalMaxPooling2D()(features)
    output = Dense(nb_classes, activation='softmax')(x)

    model = Model(input_image, output, name='DarkNetClassifier')
    return model
```

**Comment by ShilpaSangappa** [comment]
@RichardSieg : What are the changes you made to image augmentor(__getitem__ function) and the custom_loss function to use YOLO as classifier?
