### ISSUE TITLE
train on raccoon

### ISSUE THREAD

**Issue by zeynali** [experiencor/basic-yolo-keras#183]
Hi , i want to trained the full-yolo with one GTX 1080 on raccoon. 
Firstly , please see my config.json : 

```
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":            [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    20,        
        "labels":               ["raccoon"]

    },

    "train": {
        "train_image_folder":   "/home/mm/Detection-keras/basic-yolo-keras/raccoon_dataset/images/train/",
        "train_annot_folder":   "/home/mm/Detection-keras/basic-yolo-keras/raccoon_dataset/annotations/train/",     
          
        "train_times":          10,
        "pretrained_weights":   "",
        "batch_size":           12,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_raccoon.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "/home/mm/Detection-keras/basic-yolo-keras/raccoon_dataset/images/val/",
        "valid_annot_folder":   "/home/mm/Detection-keras/basic-yolo-keras/raccoon_dataset/annotations/val/",

        "valid_times":          1
    }
}
```

Now i train , Epoch 1 : current recalls are above 98 % 
http://uupload.ir/files/jv2c_screenshot_from_2018-03-14_21-54-08.png

Epoch 1 : couple of iterations : recall goes to zeros.
http://uupload.ir/files/pxfl_screenshot_from_2018-03-14_21-54-27.png

Epoch 3 , End of training , Still recall=0
http://uupload.ir/files/i2qp_screenshot_from_2018-03-14_21-57-35.png

when i tested on raccoon images , no object found .
http://uupload.ir/files/sgms_screenshot_from_2018-03-14_22-21-59.png

Why? where are the problems ?

**Comment by experiencor** [comment]
@zeynali You are doing it right but you still need to do some more work. Please read the readme carefully, especially Section 2 on warmup training and actual training.

**Comment by zeynali** [comment]
@experiencor , Hi dear , i read all of posts that you answered , You all refer to section 2. , but You did not write anything special in the section 2 , please guidance all if possible instead of refer to section 2.

**Comment by experiencor** [comment]
@zeynali oops. It should be Section 4 in your case. The specific steps are in this Section.

**Comment by zeynali** [comment]
```
**4. Start the training process**
Warm up the network

Set warmup_epochs in config.json to 3 (emperically found, 4 or 5 is also fine).

python train.py -c config.json

This process saves the trained weights to the file specified in saved_weights_name setting.
Actual network training

Set pretrained_weights setting in config.json to the warmup weights (whatever in saved_weights_name).

Set warmup_epochs in config.json to 0.

python train.py -c config.json

By the end of this process, the code will write the weights of the best model to file best_weights.h5 (or whatever name specified in the setting "saved_weights_name" in the config.json file). The training process stops when the loss on the validation set is not improved in 3 consecutive epoches.
```
I post whole of section 4 , in the `Warm up the network` don't exist special anyhing. i set  `warmup_epochs=3` , so in the `Actual network training` in the `saved_weights_name` i put my purpose name , I do not see anything special in God , You probably have eyesight.

**Comment by Sayantan17** [comment]
@zeynali How are you getting these epochs with just config.json file? Can u guide me?

**Comment by zeynali** [comment]
@Sayantan17 , Hi , i explain all my steps in above .

**Comment by Sayantan17** [comment]
Buddy @zeynali can u send this as s python file so that I can run directly the code with the changes labels . Help would be appreciated. Please. I will run directly in the Spyder (Anaconda)

**Comment by zeynali** [comment]
@Sayantan17 , you have problem in run of this codes ?

**Comment by Sayantan17** [comment]
@zeynali config.json file is ok but please provide a photo or script of your _train.py_ which you ran with this config.json u provided above. I m getting problems in train.py. Dude please provide me. Thanks

**Comment by experiencor** [comment]
@Sayantan17 What's your problem again?

**Comment by zeynali** [comment]
@Sayantan17 , please show me your error.

**Comment by Rahul9650** [comment]
@zeynali  @Sayantan17 @experiencor  The full train.py i made changes like the & the error is attached here.
import argparse
import os
import numpy as np
from preprocessing import parse_annotation
from frontend import YOLO
import json

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0"

argparser = argparse.ArgumentParser(
    description='Train and validate YOLO_v2 model on any dataset')

argparser.add_argument(
    '-c',
    '--conf',
    help='F:/downloads')

def _main_(args):

    path3="F:/downloads/config.json"

    with open(path3) as config_buffer:    
        config = json.loads(config_buffer.read())

    ###############################
    #   Parse the annotations 
    ###############################

        # parse annotations of the training set
    train_imgs, train_labels = parse_annotation(config['train']['train_annot_folder'], 
                                                config['train']['train_image_folder'], 
                                                config['model']['labels'])

    # parse annotations of the validation set, if any, otherwise split the training set
    if os.path.exists(config['valid']['valid_annot_folder']):
        valid_imgs, valid_labels = parse_annotation(config['valid']['valid_annot_folder'], 
                                                    config['valid']['valid_image_folder'], 
                                                    config['model']['labels'])
    else:
        train_valid_split = int(0.8*len(train_imgs))
        np.random.shuffle(train_imgs)

        valid_imgs = train_imgs[train_valid_split:]
        train_imgs = train_imgs[:train_valid_split]

    if len(config['model']['labels']) > 0:
        overlap_labels = set(config['model']['labels']).intersection(set(train_labels.keys()))

        print ('Seen labels:\t', train_labels)
        print ('Given labels:\t', config['model']['labels'])
        print ('Overlap labels:\t', overlap_labels)          

        if len(overlap_labels) < len(config['model']['labels']):
            print ('Some labels have no annotations! Please revise the list of labels in the config.json file!')
            return
    else:
        print ('No labels are provided. Train on all seen labels.')
        config['model']['labels'] = train_labels.keys()
        
    ###############################
    #   Construct the model 
    ###############################

    yolo = YOLO(architecture        = config['model']['architecture'],
                input_size          = config['model']['input_size'], 
                labels              = config['model']['labels'], 
                max_box_per_image   = config['model']['max_box_per_image'],
                anchors             = config['model']['anchors'])

    ###############################
    #   Load the pretrained weights (if any) 
    ###############################    

    if os.path.exists(config['train']['full_yolo_backend.h5']):
        print ("Loading pre-trained weights in", config['train']['full_yolo_backend.h5'])
        yolo.load_weights(config['train']['full_yolo_backend.h5'])

    ###############################
    #   Start the training process 
    ############################

    yolo.train(train_imgs         = train_imgs,
               valid_imgs         = valid_imgs,
               train_times        = config['train']['train_times'],
               valid_times        = config['valid']['valid_times'],
               nb_epoch           = config['train']['nb_epoch'], 
               learning_rate      = config['train']['learning_rate'], 
               batch_size         = config['train']['batch_size'],
               warmup_epochs      = config['train']['warmup_epochs'],
               object_scale       = config['train']['object_scale'],
               no_object_scale    = config['train']['no_object_scale'],
               coord_scale        = config['train']['coord_scale'],
               class_scale        = config['train']['class_scale'],
               saved_weights_name = config['train']['saved_weights_name'],
               debug              = config['train']['debug'])

if __name__ == '__main__':
    args = argparser.parse_args()
    _main_(args)

error -Traceback (most recent call last):

  File "<ipython-input-30-a0e9113b4440>", line 101, in <module>
    _main_(args)

  File "<ipython-input-30-a0e9113b4440>", line 24, in _main_
    config = json.loads(config_buffer.read())

  File "C:\Users\rah96\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)

  File "C:\Users\rah96\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\rah96\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)

JSONDecodeError: Expecting ',' delimiter
 

Urgent help would be appreciated.

**Comment by Sayantan17** [comment]
@zeynali Buddy the error Is attached with the file . Please help to get it sorted out.

**Comment by Sayantan17** [comment]
@zeynali Can you please guide us as you achieve success in running this file!

**Comment by zeynali** [comment]
what's this ? `path3="F:/downloads/config.json"` Never go this way. the parseargs are for this ways. you can download again this codes and only just modify config.json file no others files , and follow those commands , sure you will can train.

**Comment by Sayantan17** [comment]
Only shall I modify path like yours & no change in train.py right?

**Comment by Sayantan17** [comment]
@zeynali my initial config.json file is this & i have not changed even a single word in train.py
`{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "/Users/sayantanbhattacharya/Documents/GitHub/basic-yolo-keras/Raccoon Dataset/train_image_folder/",
        "train_annot_folder":   "/Users/sayantanbhattacharya/Documents/GitHub/basic-yolo-keras/Raccoon Dataset/train_image_folder/",     
          
        "train_times":          10,
        "pretrained_weights":   "/Users/sayantanbhattacharya/Documents/GitHub/basic-yolo-keras/Raccoon Dataset/full_yolo_raccoon.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,
        "saved_weights_name":   ""
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}`
the error is like this when i run the script 
**_Sayantans-MBP:~ sayantanbhattacharya$ python train.py -c config.json
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    _main_(args)
  File "train.py", line 66, in _main_
    config = json.loads(config_buffer.read())
  File "/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/anaconda3/lib/python3.6/json/decoder.py", line 326, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/lib/python3.6/json/decoder.py", line 340, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 26 column 9 (char 1126)_**
 What is the error i think error is file if so please guide me!

**Comment by zeynali** [comment]
@Sayantan17 probably because you run by python3.6 . try run this by python2.7

**Comment by Sayantan17** [comment]
@zeynali Any any alternative? I am struck in this step for past few days?

**Comment by Sayantan17** [comment]
@zeynali  Same error i am getting i even degraded to python 2.7
![screen shot 2018-03-18 at 10 45 43](https://user-images.githubusercontent.com/37222844/37562928-1a777f54-2a9a-11e8-9c15-dc569fd01e04.png)
Please help.
