### ISSUE TITLE
The question of Train on my own dataset

### ISSUE THREAD

**Issue by jacobssy** [experiencor/basic-yolo-keras#185]
Hi,
Thanks for sharing your Code, I follow your Yolo Step-by-Step.ipynb to train my own dataset about Traffic Sign, which includes 43 classes,and the image is (50-90)pixs in x,y ,here I have a question about the generate config: 
1,Object Scale ,COORD_SCALE,CLASS_SCLAE
2, Anchors,True_Box_Buffer.
how do you get their value?
I nearly follow your configuration, resize the input to 416*416,I want to know  whether I should change the true value{xmin,ymin,xmax,ymax} ,because I think when I change resize the input  to 416*416,The true box information should change to adapt the input. Am I right? 
Thanks!

**Comment by experiencor** [comment]
@jacobssy I don't need to manually resize the input to 416. You just need to specify 416 in the input_size in config.json. The code will auto resize the images before feeding them to the model during training and testing.

**Comment by jacobssy** [comment]
@experiencor yeah,thanks for replying, I mean, whether the true box values{xmin,ymin,xmax,ymax}should be changed to adapt the 416,for example, my data is 60 pixs, the box value is {6,7,48,56},whether I should change the value? sorry for my  simple  question...

**Comment by zeynali** [comment]
these codes also automatically resize these values of BBox the same aspect-ration that images resized.

**Comment by jacobssy** [comment]
@zeynali Thank you! I will try to understand the code .
