### ISSUE TITLE
Error in the code 'Yolo step by step.ipynb'

### ISSUE THREAD

**Issue by Rahul9650** [experiencor/basic-yolo-keras#186]
Hello @experiencor I am getting the error in the middle of the step.
 The code is like this:-
wt_path = 'F:/downloads/tiny_yolo_backend.h5'                     
train_image_folder = 'F:/downloads/train_image_folder'
train_annot_folder = 'F:/downloads/train_annot_folder'
valid_image_folder = 'F:/downloads/valid_image_folder'
valid_annot_folder = 'F:/downloads/valid_annot_folder'

weight_reader = WeightReader(wt_path)
weight_reader.reset()
nb_conv = 23

for i in range(1, nb_conv+1):
    conv_layer = model.get_layer('conv_' + str(i))
    
    if i < nb_conv:
        norm_layer = model.get_layer('norm_' + str(i))
        
        size = np.prod(norm_layer.get_weights()[0].shape)

        beta  = weight_reader.read_bytes(size)
        gamma = weight_reader.read_bytes(size)
        mean  = weight_reader.read_bytes(size)
        var   = weight_reader.read_bytes(size)

        weights = norm_layer.set_weights([gamma, beta, mean, var])       
        
    if len(conv_layer.get_weights()) > 1:
        bias   = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[1].shape))
        kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
        kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
        kernel = kernel.transpose([2,3,1,0])
        conv_layer.set_weights([kernel, bias])
    else:
        kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
        kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
        kernel = kernel.transpose([2,3,1,0])
        conv_layer.set_weights([kernel])

& I am getting error like this -
**_---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-0604c1b5bbd1> in <module>()
     27     else:
     28         kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
---> 29         kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
     30         kernel = kernel.transpose([2,3,1,0])
     31         conv_layer.set_weights([kernel])

ValueError: cannot reshape array of size 643606 into shape (1024,512,3,3)_**

Can you help to sort this issue. Help'ld be appreciated.
Thank you.

**Comment by zeynali** [comment]
i have same problem.

**Comment by experiencor** [comment]
@Rahul9650 @zeynali Sorry for not specifying clearly. The notebook is exclusive for FullYolo. You need to change the architecture in ```Construct the network``` section if you want to use TinyYolo. TinyYolo architecture can be found in backend.py.

**Comment by Rahul9650** [comment]
@experiencor  Sir Where is the **Construct the network** ?

**Comment by omnaathharis** [comment]
Hi 
I have get this error when running in full yolo weights
weight_reader.reset()
nb_conv = 23

for i in range(1, nb_conv+1):
    conv_layer = model.get_layer('conv_' + str(i))
    print("Conv")
    print(i)
    
    if i < nb_conv:
        norm_layer = model.get_layer('norm_' + str(i))
        print("Norm")
        print(i)
        
        size = np.prod(norm_layer.get_weights()[0].shape)

        beta  = weight_reader.read_bytes(size)
        gamma = weight_reader.read_bytes(size)
        mean  = weight_reader.read_bytes(size)
        var   = weight_reader.read_bytes(size)

        weights = norm_layer.set_weights([gamma, beta, mean, var])       
        
    if len(conv_layer.get_weights()) > 1:
        bias   = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[1].shape))
        kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
        kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
        kernel = kernel.transpose([2,3,1,0])
        conv_layer.set_weights([kernel, bias])
    else:
        kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
        kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
        kernel = kernel.transpose([2,3,1,0])
        conv_layer.set_weights([kernel])
        
print("Layer Weighted")
help me to resolve 
Thanks

**Comment by omnaathharis** [comment]
error is
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-f68193427ca3> in <module>()
     24         bias   = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[1].shape))
     25         kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
---> 26         kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
     27         kernel = kernel.transpose([2,3,1,0])
     28         conv_layer.set_weights([kernel, bias])

ValueError: cannot reshape array of size 41237 into shape (425,1024,1,1)

**Comment by omnaathharis** [comment]
Hi experiencor
 train_imgs, seen_train_labels = parse_annotation(train_annot_folder, train_image_folder, labels=LABELS)
### write parsed annotations to pickle for fast retrieval next time
#with open('train_imgs', 'wb') as fp:
#    pickle.dump(train_imgs, fp)

### read saved pickle of parsed annotations
#with open ('train_imgs', 'rb') as fp:
#    train_imgs = pickle.load(fp)
train_batch = BatchGenerator(train_imgs, generator_config, norm=normalize)

valid_imgs, seen_valid_labels = parse_annotation(valid_annot_folder, valid_image_folder, labels=LABELS)
### write parsed annotations to pickle for fast retrieval next time
#with open('valid_imgs', 'wb') as fp:
#    pickle.dump(valid_imgs, fp)

### read saved pickle of parsed annotations
#with open ('valid_imgs', 'rb') as fp:
#    valid_imgs = pickle.load(fp)
valid_batch = BatchGenerator(valid_imgs, generator_config, norm=normalize, jitter=False)
why I'm getting this error
help me to resolve

**Comment by omnaathharis** [comment]
OSError                                   Traceback (most recent call last)
<ipython-input-21-8d00644db510> in <module>()
----> 1 train_imgs, seen_train_labels = parse_annotation(train_annot_folder, train_image_folder, labels=LABELS)
      2 ### write parsed annotations to pickle for fast retrieval next time
      3 #with open('train_imgs', 'wb') as fp:
      4 #    pickle.dump(train_imgs, fp)
      5 

/home/object_detection/haris/basic-yolo-keras/preprocessing.pyc in parse_annotation(ann_dir, img_dir, labels)
     13     seen_labels = {}
     14 
---> 15     for ann in sorted(os.listdir(ann_dir)):
     16         img = {'object':[]}
     17 

OSError: [Errno 2] No such file or directory: '/haris/basic-yolo-keras/raccoon_dataset/annotations/'
I'm getting this error while running "Parse the annotations to construct train generator and validation generator"
how to resolve 
Thanks in advance

**Comment by omnaathharis** [comment]
Yup.But I have correctly  mentioned the directory and also there is directory in that location. but I don't know why this error is occuring

**Comment by omnaathharis** [comment]
oops sorry @experiencor  its my typo_error

**Comment by hiba007** [comment]
@Rahul9650 i have the similar problem but I solved it check  the length of labels it must be 80

**Comment by zeynali** [comment]
@hiba007 ,Hi , please more explain about this and put all of your change in codes.

**Comment by pksnkl** [comment]
I just downloaded this Yolo step by step.ipynb file and changed path.
What is error in this code? Pls help.
 my code is 
wt_path = 'E:\\Deep Learning\\keras-yolo2-master\\keras-yolo2\\cocoDATASET\\yolo.weights'                      
train_image_folder = 'E:\\Deep Learning\\keras-yolo2-master\\keras-yolo2\\cocoDATASET\\train2014\\train2014'
#train_annot_folder = 'E:\Deep Learning\keras-yolo2-master\keras-yolo2\cocoDATASET\train2014ann'
train_annot_folder = 'E:\\Deep Learning\\keras-yolo2-master\\keras-yolo2\\cocoDATASET\\train2014ann'
valid_image_folder = 'E:\\Deep Learning\\keras-yolo2-master\\keras-yolo2\\cocoDATASET\\val2014\\val2014'
valid_annot_folder = 'E:\\Deep Learning\\keras-yolo2-master\\keras-yolo2\\cocoDATASET\\val2014ann'

All the folders and corresponding files avail in that location.

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-8d00644db510> in <module>()
----> 1 train_imgs, seen_train_labels = parse_annotation(train_annot_folder, train_image_folder, labels=LABELS)
      2 ### write parsed annotations to pickle for fast retrieval next time
      3 #with open('train_imgs', 'wb') as fp:
      4 #    pickle.dump(train_imgs, fp)
      5 

C:\Users\pk\keras-yolo2\preprocessing.py in parse_annotation(ann_dir, img_dir, labels)
     16         img = {'object':[]}
     17 
---> 18         tree = ET.parse(ann_dir + ann)
     19 
     20         for elem in tree.iter():

C:\Users\pk\Anaconda3\lib\xml\etree\ElementTree.py in parse(source, parser)
   1194     """
   1195     tree = ElementTree()
-> 1196     tree.parse(source, parser)
   1197     return tree
   1198 

C:\Users\pk\Anaconda3\lib\xml\etree\ElementTree.py in parse(self, source, parser)
    584         close_source = False
    585         if not hasattr(source, "read"):
--> 586             source = open(source, "rb")
    587             close_source = True
    588         try:

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Deep Learning\\keras-yolo2-master\\keras-yolo2\\cocoDATASET\\train2014anncaptions_train2014.json'

**Comment by esconda** [comment]
Full-Yolo file is not available in shared files.Could you please add it(tiny-yolo is available)
