### ISSUE TITLE
Last step jupyter error-

### ISSUE THREAD

**Issue by Sayantan17** [experiencor/basic-yolo-keras#189]
hello @experiencor  @experiencor  In the jupyter code,

![screen shot 2018-03-17 at 23 02 18](https://user-images.githubusercontent.com/37222844/37558287-83d83cd0-2a37-11e8-8227-517d4fbe5987.png)
![screen shot 2018-03-17 at 23 03 01](https://user-images.githubusercontent.com/37222844/37558289-8793ce16-2a37-11e8-9189-6c80a9887bde.png)

 We are getting error in the last step which are attached here. Please help to get this issue sorted out soon.

**Comment by experiencor** [comment]
Is that folder not available there?

**Comment by Sayantan17** [comment]
@experiencor preprocess.py is available there.

**Comment by Sayantan17** [comment]
@experiencor @experiencor  I think i have resolved the previous error & the file directories are **attached** & i think i am getting the error in XML strings which is also attached with error. 
![screen shot 2018-03-18 at 17 53 52](https://user-images.githubusercontent.com/37222844/37565788-e2f702c0-2ad5-11e8-86c2-104dc9877b90.png)
![screen shot 2018-03-18 at 17 54 15](https://user-images.githubusercontent.com/37222844/37565789-e3f1c7a0-2ad5-11e8-9f19-c8f66c79c4ff.png)

Thanking you. Urgent help would be appreciated.

**Comment by Sayantan17** [comment]
But @experiencor how did you get Tensorflow which is applicable for Python 2.7 ?

**Comment by experiencor** [comment]
@Sayantan17 I use tensorflow 1.1 (pip install tensorflow==1.1).
