### ISSUE TITLE
Add accuracy 

### ISSUE THREAD

**Issue by ziedbouf** [experiencor/basic-yolo-keras#19]
@experiencor  what do you think about the used accuracy within darkflow project (Yolo implementation), https://github.com/thtrieu/darkflow/pull/377

**Comment by experiencor** [comment]
This evaluation metric is rather strange. I think that it is often used in classification. Evaluating object detection is quite different from evaluating classification. E.g., we don't have true negative in object detection. People usually use precision and recall to evaluate object detection result. See https://stats.stackexchange.com/questions/260430/average-precision-in-object-detection and https://en.wikipedia.org/wiki/Precision_and_recall.

**Comment by experiencor** [comment]
@ziedbouf the link you provided is talking in classification setting. In object detection, for each ground truth box, it is either detected by the algorithm (called true positive) or not detected (called false negative). For each detected box, it is either a true detection (called true positive) or a wrong detection (called false postive).

True negative makes any sense in object detection?

**Comment by Pezaun** [comment]
True negative does not make sense in object detection! You can't miss a box prediction of some thing that does not exist in a image.

Regards
