### ISSUE TITLE
Does anyone have a full working example I could look at?

### ISSUE THREAD

**Issue by franksRsrch** [experiencor/basic-yolo-keras#193]
Does anyone have a simple working example that I could look at, please? In the style of the step-by-step.

I've tried to get the blood cell example to work (previous post). I've also tried the 'step-by-step' code but python can't find the files (I've noticed that the bloodcell example appends .jpg to the files, but the step-by-step doesn't).

**Comment by franksRsrch** [comment]
Here is the json file I use where I get the error:

```
{
    "model" : {
        "architecture":         "Full Yolo", 
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "./images/",
        "train_annot_folder":   "./annotations/",     
          
        "train_times":          10,
        "pretrained_weights":   "full_yolo_backend.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "output_yolo_raccoon.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}

```

The command I use is: `python3 train.py -c config.json`

**Comment by experiencor** [comment]
@franksRsrch I find that it's very easy to train raccoon, blood cell, and kangaroo detectors using the datasets that I provided and the FullYolo backend. But some of you guys do have troubles getting the code to work. All I can say is that you need to follow the readme closely and try a few times. Training deep net requires a lot of patience :grin:.
