### ISSUE TITLE
train own dataset

### ISSUE THREAD

**Issue by Heidisnaps** [experiencor/basic-yolo-keras#2]
Hi. I want to train with my own dataset.
I want to use my dataset or only a part of the VOC dataset (for example, learn only three classes of people, dog, cat).
The pre-trainning model has 20 classes and loads the tiny-yolo-voc.weights file.
But I want to train without tiny-yolo-voc.weights. What should I do?

**Comment by zenineasa** [comment]
Just ignore the load pretrained weights section. It should work, i guess...

**Comment by Jonas1312** [comment]
First you need xml annotations files, you can generate them using [LABELIMG](https://github.com/tzutalin/labelImg).
As zenineasa said it, just ignore the load pretrained weights section and modify:
```
LABELS = [...]

COLORS = [...]

CLASS = 3

# Layer 9
model.add(Conv2D(BOX * (4 + 1 + CLASS), (1, 1), strides=(1, 1), kernel_initializer='he_normal'))
model.add(Activation('linear'))
model.add(Reshape((GRID_H, GRID_W, BOX, 4 + 1 + CLASS)))
```

**Comment by Heidisnaps** [comment]
@zenineasa thanks ignore the weight.
and it work.

@Jonas1312 thanks!! I tried your solution and it work.
now I training.

**Comment by experiencor** [comment]
@Heidisnaps @zenineasa @Jonas1312 you guys are awesome. I will fix layer 9 accordingly.
