### ISSUE TITLE
You are trying to load a weight file containing 44 layers into a model with 45 layers.

### ISSUE THREAD

**Issue by khoaprogrammer** [experiencor/basic-yolo-keras#20]
Cannot load full yolo pretrain weight, please help!

**Comment by experiencor** [comment]
I guessed that you trying to directly load the pretrained weights provided by me in the readme. This file should not be used in this way as it only contains the weights of all layers except the last layer. The layer depends on the number of the classes, hence I don't provide the weight for this layer. 

What I mean in the last issue that you created is that you can load the pretrained weights that the model has created during training to continue the training process. Don't have to start from scratch. Sorry for the confusion.

**Comment by friendmine** [comment]
hello, I met the same question, how did you resolve it? 
thanks

**Comment by friendmine** [comment]
I've met the same question, because of using wrong weight

**Comment by mdawas** [comment]
@friendmine where did you find the right weights? I ran into the same problem but I couldn't find the correct full_yolo_backend.h5 file on the onedrive that is mentioned in the readme file.

**Comment by rodrigo2019** [comment]
Using keras version 2.1.5 and tensorflow 1.7.0
with these weights: https://github.com/rodrigo2019/keras-yolo2/releases/download/pre-trained-weights/full_yolo_backend.h5
and with this repository: https://github.com/rodrigo2019/keras-yolo2
I'm able to load the pre trained weights without problems

**Comment by mdawas** [comment]
@rodrigo2019 Thanks for the reply!
I am using the weights file you mentioned but with this repository: https://github.com/experiencor/keras-yolo2
I am not using your fork, is there a substantial difference between them both? I mean the network design is the same.
Another question, what would happen if I don't use the backend weights? Can I still train a good model? or I will need to train for a longer time?

**Comment by rodrigo2019** [comment]
@mdawas  take a look here #291, in fact I got better results training from scracth instead training using these pre trained weights.
In my fork I did some modification in the loss function, so using my fork you can get a little better results. Also you can train with rectangular images and not just in squares images like this fork

**Comment by mdawas** [comment]
@rodrigo2019 I forked your repo now, I started to play around with the it but I am facing some problems with the config file :(. are there any comments about the properties in the config? as it's a bit different than the original version!

**Comment by rodrigo2019** [comment]
which problems?

**Comment by mdawas** [comment]
Mainly now I get an error when I try to run gen_anchors.py, the error is about loading the config file:
'Traceback (most recent call last):
  File "$/gen_anchors.py", line 147, in <module>
    main(args)
  File "$/gen_anchors.py", line 109, in main
    config = json.loads(config_buffer.read())
  File "$/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "$/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "$/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 55 column 5 (char 1649)
'
P.S: I use python 2.7.15.
