### ISSUE TITLE
The format of input

### ISSUE THREAD

**Issue by MatejMatula** [experiencor/basic-yolo-keras#208]
I would like to add custom dataset, however what format should it have? I cannot find anything about it. I mean about inputing data into network. Having 13  x 13 x 5 x 85 output. How would example of input data be if there was jut one object? I am not talking about xml notations, but representation in numpy array

**Comment by experiencor** [comment]
Hi @MatejMatula! An input is simply a jpg image. Check out https://github.com/experiencor/raccoon_dataset/tree/master/images.

**Comment by MatejMatula** [comment]
I didnt make it clear, i was talking about label input data.

**Comment by experiencor** [comment]
@MatejMatula hmm. It's quite complicated. You look at https://github.com/experiencor/basic-yolo-keras/blob/master/preprocessing.py for details.
