### ISSUE TITLE
divided by 255.

### ISSUE THREAD

**Issue by Kevin-Moon** [experiencor/basic-yolo-keras#21]
in the below code, why did you divide image by 255 ONLY in 'Predict' function?
and why not in 'Training' function?

Don't we need to divide them in both cases?

```
    def preprocess(self, image):
        input_image = cv2.resize(image, (self.input_size, self.input_size))
        input_image = **input_image / 255.**
```

thank you!

**Comment by experiencor** [comment]
Dividing by 255. is the preprocessing step of YOLO. During training, it's performed in the BatchGenerator class. Please refer to line 197 of file preprocessing.py. Perhaps, I should be more consistent in the use of the normalize function.

**Comment by Kevin-Moon** [comment]
Aha! it's clear!!  thank you.
