### ISSUE TITLE
KeyError: 'backend'

### ISSUE THREAD

**Issue by jashshopin** [experiencor/basic-yolo-keras#215]
I am getting the following error when I try to run the code on the raccoon data set. This is a new problem that I faced after cloning the repository today. I could successfully run the code when I had cloned the repository on 20 March 2018.

Could you help me solve this problem?

```
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    _main_(args)
  File "train.py", line 66, in _main_
    yolo = YOLO(backend             = config['model']['backend'],
KeyError: 'backend'
```

**Comment by experiencor** [comment]
@jashshopin It's fixed now.

**Comment by hamburgerBear** [comment]
I have a problem,when i run https://github.com/experiencor/keras-yolo2  code to train raccoon dataset
I input "python train.py -c config.json"  on 3 JULY,  

Using TensorFlow backend.
('Seen labels:\t', {'raccoon': 217})
('Given labels:\t', [u'raccoon'])
('Overlap labels:\t', set(['raccoon']))
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    _main_(args)
  File "train.py", line 66, in _main_
    yolo = YOLO(backend             = config['model']['backend'],
KeyError: 'backend'

**Comment by hamzatanvir** [comment]
> I am getting the following error when I try to run the code on the raccoon data set. This is a new problem that I faced after cloning the repository today. I could successfully run the code when I had cloned the repository on 20 March 2018.
> 
> Could you help me solve this problem?
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 101, in <module>
>     _main_(args)
>   File "train.py", line 66, in _main_
>     yolo = YOLO(backend             = config['model']['backend'],
> KeyError: 'backend'
> ```

how did you resolved this error?
