### ISSUE TITLE
How does directory structure look like for this project?

### ISSUE THREAD

**Issue by bexx1963** [experiencor/basic-yolo-keras#220]
![grafik](https://user-images.githubusercontent.com/28936520/38217197-ba0280f2-36cd-11e8-994c-ca610fff3abb.png)

these are my files and folders but running train.py is ending with an error:
**'Some labels have no annotations! Please revise the list of labels in the config.json file!'**

**Comment by bexx1963** [comment]
![grafik](https://user-images.githubusercontent.com/28936520/38217324-43863d82-36ce-11e8-9d1d-8c3eac21f883.png)

**Comment by experiencor** [comment]
@bexx1963 your spelling of ```raconn``` in the config file is wrong, it should be ```raccoon```.
