### ISSUE TITLE
Why it creates many threads while training?

### ISSUE THREAD

**Issue by ndaidong** [experiencor/basic-yolo-keras#224]
Hi everybody,

I'm just curious why when I run `train.py`, it creates so much threads? Is it TensorFlow's mechanism of process management?

![Many threads while training](https://user-images.githubusercontent.com/1809619/38300712-bd162252-3827-11e8-897f-2a50ed05eae0.png)

Thanks in advance.

**Comment by experiencor** [comment]
@ndaidong Multiple threads read images simultaneously. This is to solve the bottleneck when your GPU is faster than the speed of data feeding. Control the number of threads via ```max_queue_size``` in frontend.py.

**Comment by ndaidong** [comment]
@experiencor thank you.
