### ISSUE TITLE
Issues Training

### ISSUE THREAD

**Issue by KeeganVG** [experiencor/basic-yolo-keras#23]
Error:

Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    _main_(args)
  File "train.py", line 103, in _main_
    anchors             = config['model']['anchors'])
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/models.py", line 213, in __init__
    output = Reshape((self.grid_h, self.grid_w, self.nb_box, 4 + 1 + self.nb_class))(x)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/keras/layers/core.py", line 392, in call
    return K.reshape(inputs, (-1,) + target_shape)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1722, in reshape
    return tf.reshape(x, shape)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in reshape
    name=name)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 589, in apply_op
    param_name=input_name)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

Config file:
{
    "model" : {
        "architecture":         "Tiny Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    1,
        "labels":               ["M4A1 Tank"]
    },

    "train": {
        "train_image_folder":   "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/train_image_folder/",
        "train_annot_folder":   "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/train_annot_folder/",

        "train_times":          10,
        "pretrained_weights":   "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/tiny.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_batches":       100,

        "object_scale":         5.0,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "debug":                false
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }

Any ideas?

**Comment by experiencor** [comment]
It seems that self.grid_h and self.grid_w happen to receive floating point values instead of the expected int values (should be 13 = 41/32 in this case). Can you print out self.grid_h, self.grid_w? I guess that you attempt to change the architecture of Tiny Yolo.

**Comment by KeeganVG** [comment]
I dont see how I would have modified Tiny's Architecture? The only change I made was reducing the number of classes detect to the single object.

I'll print them out and see what happens.

**Comment by supernihui** [comment]
I have met the same error and I have found solutions. It's quite simple because self.grid_h is divided by some numbers which make it a "float" instead of "int". You can find the code in model.py like self.grid_h=input_size/32 and alter it: self.grid_h=int(input_size/32)

**Comment by KeeganVG** [comment]
Thanks! That worked great...its actually loading the net now...any idea why im getting a layer mismatch though?

Using TensorFlow backend.
2017-10-15 11:28:30.751860: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 11:28:30.751882: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 11:28:30.751886: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 11:28:30.751889: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 11:28:30.751891: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
input_1 (InputLayer)             (None, 416, 416, 3)   0                                            
____________________________________________________________________________________________________
conv_1 (Conv2D)                  (None, 416, 416, 16)  432         input_1[0][0]                    
____________________________________________________________________________________________________
norm_1 (BatchNormalization)      (None, 416, 416, 16)  64          conv_1[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_1 (LeakyReLU)        (None, 416, 416, 16)  0           norm_1[0][0]                     
____________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)   (None, 208, 208, 16)  0           leaky_re_lu_1[0][0]              
____________________________________________________________________________________________________
conv_2 (Conv2D)                  (None, 208, 208, 32)  4608        max_pooling2d_1[0][0]            
____________________________________________________________________________________________________
norm_2 (BatchNormalization)      (None, 208, 208, 32)  128         conv_2[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_2 (LeakyReLU)        (None, 208, 208, 32)  0           norm_2[0][0]                     
____________________________________________________________________________________________________
max_pooling2d_2 (MaxPooling2D)   (None, 104, 104, 32)  0           leaky_re_lu_2[0][0]              
____________________________________________________________________________________________________
conv_3 (Conv2D)                  (None, 104, 104, 64)  18432       max_pooling2d_2[0][0]            
____________________________________________________________________________________________________
norm_3 (BatchNormalization)      (None, 104, 104, 64)  256         conv_3[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_3 (LeakyReLU)        (None, 104, 104, 64)  0           norm_3[0][0]                     
____________________________________________________________________________________________________
max_pooling2d_3 (MaxPooling2D)   (None, 52, 52, 64)    0           leaky_re_lu_3[0][0]              
____________________________________________________________________________________________________
conv_4 (Conv2D)                  (None, 52, 52, 128)   73728       max_pooling2d_3[0][0]            
____________________________________________________________________________________________________
norm_4 (BatchNormalization)      (None, 52, 52, 128)   512         conv_4[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_4 (LeakyReLU)        (None, 52, 52, 128)   0           norm_4[0][0]                     
____________________________________________________________________________________________________
max_pooling2d_4 (MaxPooling2D)   (None, 26, 26, 128)   0           leaky_re_lu_4[0][0]              
____________________________________________________________________________________________________
conv_5 (Conv2D)                  (None, 26, 26, 256)   294912      max_pooling2d_4[0][0]            
____________________________________________________________________________________________________
norm_5 (BatchNormalization)      (None, 26, 26, 256)   1024        conv_5[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_5 (LeakyReLU)        (None, 26, 26, 256)   0           norm_5[0][0]                     
____________________________________________________________________________________________________
max_pooling2d_5 (MaxPooling2D)   (None, 13, 13, 256)   0           leaky_re_lu_5[0][0]              
____________________________________________________________________________________________________
conv_6 (Conv2D)                  (None, 13, 13, 512)   1179648     max_pooling2d_5[0][0]            
____________________________________________________________________________________________________
norm_6 (BatchNormalization)      (None, 13, 13, 512)   2048        conv_6[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_6 (LeakyReLU)        (None, 13, 13, 512)   0           norm_6[0][0]                     
____________________________________________________________________________________________________
max_pooling2d_6 (MaxPooling2D)   (None, 13, 13, 512)   0           leaky_re_lu_6[0][0]              
____________________________________________________________________________________________________
conv_7 (Conv2D)                  (None, 13, 13, 1024)  4718592     max_pooling2d_6[0][0]            
____________________________________________________________________________________________________
norm_7 (BatchNormalization)      (None, 13, 13, 1024)  4096        conv_7[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_7 (LeakyReLU)        (None, 13, 13, 1024)  0           norm_7[0][0]                     
____________________________________________________________________________________________________
conv_8 (Conv2D)                  (None, 13, 13, 1024)  9437184     leaky_re_lu_7[0][0]              
____________________________________________________________________________________________________
norm_8 (BatchNormalization)      (None, 13, 13, 1024)  4096        conv_8[0][0]                     
____________________________________________________________________________________________________
leaky_re_lu_8 (LeakyReLU)        (None, 13, 13, 1024)  0           norm_8[0][0]                     
____________________________________________________________________________________________________
conv_9 (Conv2D)                  (None, 13, 13, 30)    30750       leaky_re_lu_8[0][0]              
____________________________________________________________________________________________________
reshape_1 (Reshape)              (None, 13, 13, 5, 6)  0           conv_9[0][0]                     
____________________________________________________________________________________________________
input_2 (InputLayer)             (None, 1, 1, 1, 1, 4) 0                                            
____________________________________________________________________________________________________
lambda_1 (Lambda)                (None, 13, 13, 5, 6)  0           reshape_1[0][0]                  
                                                                   input_2[0][0]                    
====================================================================================================
Total params: 15,770,510
Trainable params: 15,764,398
Non-trainable params: 6,112
____________________________________________________________________________________________________
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    _main_(args)
  File "train.py", line 110, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/models.py", line 382, in load_weights
    self.model.load_weights(weight_path)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/keras/engine/topology.py", line 2619, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/yoloKeras/lib/python3.5/site-packages/keras/engine/topology.py", line 3068, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 16 layers into a model with 17 layers.
(yoloKeras) ------------------------------------------------------------

**Comment by KeeganVG** [comment]
Traceback (most recent call last):
  File "trainK.py", line 132, in <module>
    _main_(args)
  File "trainK.py", line 128, in _main_
    debug            = False)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/models.py", line 548, in train
    train_batch = BatchGenerator(train_imgs, generator_config)
  File "/home/alihusain/Documents/yoloConversion/keras/basic-yolo-keras/preprocessing.py", line 67, in __init__
    self.anchors = [BoundBox(0, 0, config['ANCHORS'][2*i], config['ANCHORS'][2*i+1]) for i in range(len(config['ANCHORS'])/2)]
TypeError: 'float' object cannot be interpreted as an integer
(yoloKeras) ------------------------------------------------------------

Ideas?

**Comment by supernihui** [comment]
In fact, that's because the last line ANCHORS/2 is a float, you should also use a int(x) to make the code run.

**Comment by KeeganVG** [comment]
Thanks alot guys I was able to get it training.

Quick question, is there a way to run it on my graphics cards?

**Comment by HariP1234** [comment]
Hi guys,
I just started with this project. I am also getting the same error as KeeganVG.
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64
There is a models.py in basic-yolo-keras-master\venv\Lib\site-packages\pip\_vendor\requests. But it does not have self.grid_h.
I have posted my issue in #199 .
Please help me.
