### ISSUE TITLE
Slow training speed

### ISSUE THREAD

**Issue by KeeganVG** [experiencor/basic-yolo-keras#25]
Training speed is very slow...almost 2000s per epoch on a dataset of 300 images.

I'm using the train.py because I haven't yet figured out how to get tiny-yolo working through the jupyter implementation (i'm still working on it though so I'll keep everyone updated!). 

I'm almost maxed out on CPU usage...but my GPU usage is nothing. Does anyone have any suggestions on how to offload some work onto the GPU, or a working jupyter implementation of tiny yolo?

**Comment by supernihui** [comment]
Because you didn't use the GPU. You can just test tensorflow gpu test is ok first and then do this yolo test.

**Comment by experiencor** [comment]
@supernihui is right. Training on CPU is very slow. You need to figure out how to install the GPU version of tensorflow (https://www.tensorflow.org/install/install_linux).
