### ISSUE TITLE
Problem when detect hand palm with the model

### ISSUE THREAD

**Issue by khoaprogrammer** [experiencor/basic-yolo-keras#26]
Hi, i'm trying to use Full Yolo model to train and detect hand palm. I loaded the pretrain weight and try to test the model with 10 pic to train and 2 pic to test. After train about 17 epochs, the model can predict the box correctly but it also predict some mini box within that box with higher score than the main box. Please help. This is a result pic:

https://i.imgur.com/h1BpflZ.jpg

**Comment by experiencor** [comment]
So the problem is that there are so many boxes activated. It's usually because of not enough training. I would suggest you train a couple more epochs.

The other thing is that your dataset is too small. Try to collect more data, such as from http://www.robots.ox.ac.uk/~vgg/data/hands/.
