### ISSUE TITLE
Link for hand detection dataset is not correct. 

### ISSUE THREAD

**Issue by hardik124** [experiencor/basic-yolo-keras#29]
[ ](url)

**Comment by experiencor** [comment]
My mistake! The hand detection dataset is not available as it is not owned by me. The result is shared by the author of the dataset.

**Comment by experiencor** [comment]
@hardik124 It's here http://cvrr.ucsd.edu/vivachallenge/index.php/hands/hand-detection/.

**Comment by hardik124** [comment]
Thank you
