### ISSUE TITLE
How to fit kitti image shape?

### ISSUE THREAD

**Issue by jinfagang** [experiencor/basic-yolo-keras#31]
Hi, experiencor, sorry for bother, but may I have some questions about train and prediction?

```
1. I want train on kitti, to detect Car and Pedestrian and etc, but kitti image shape is (1274, 375),
 but yolo input size is square and it's 416, if I leave it in 416, then then image would be crop too
 much, and the height is not that enough, so what should I set the inputsize?
2. If I changed the input size, should I edit the net structure?
```
Really helps for your advise!

**Comment by experiencor** [comment]
@jinfagang 

1. The images will not be cropped. They will be resized. You will not lose anything. The bigger the size, the more accurate but slower the prediction. The aspect ratio of the kitti image is highly unbalanced, hence you may want to try uneven input size like (416, 224). It will work in principle but the code may break here and there. Please tell me if it does.

2. You don't have to edit anything. The net structure is designed to work with custom input size.

**Comment by jinfagang** [comment]
So many thanks for generally reply.

You mentioned that image will be resized, if I put kitti image into a (416, 416) input shape (also we can let data shape be (416, 224), so wider), but what ever in these cases, the image resized will be stretched or shrinked, then the car or other object will not be the right size, especially the label may not right transformed with image (resize maybe will, but crop should hard to let labeled box change with original image). 

So, if I train on kitti, maybe I just need change the input data shape into (416, 224)? but how to preprocess with original image? If simply resize, will occurred problems as I mentioned above.

Do you have any higher opinion on these puzzles?

**Comment by experiencor** [comment]
You don't have to worry about that. The code does change the labels (size and position of the bounding box) according to how it changes the image. You may want to look at function aug_image in my preprocessing.py file. It resizes, jitters, and randrom crops the images. It then fixes the labels accordingly.
