### ISSUE TITLE
There is an error in predicting use weights from other machine .  

### ISSUE THREAD

**Issue by stephen-v** [experiencor/basic-yolo-keras#37]
hi，the error is  " You are trying to load a weight file containing 2 layers into a model with 44 layers " .

**Comment by stephen-v** [comment]
but when i  modify  ‘backend.py’ line 162 

`self.feature_extractor.load_weights(FULL_YOLO_FEATURE_PATH) `
to
 `self.feature_extractor.load_weights(FULL_YOLO_FEATURE_PATH,by_name=True)`

solve it !

**Comment by experiencor** [comment]
Sorry for not being clear enough. You may have used the wrong weight file. Please read **Section 2. Edit the configuration file** carefully.

**Comment by stephen-v** [comment]
the weight is correct , it can be ran in training's machine .

**Comment by experiencor** [comment]
@stephen-v How's the result? I guess that it's not good as the weights of the backend is not loaded properly if you use ```by_name=True```. It only loads the layers with the names present in the weight file. The other layers are igored.

**Comment by stephen-v** [comment]
the result seem to be correct . same code , we trained in Linux  and ran in windows
