### ISSUE TITLE
The code in preprocessing.py  line175 176

### ISSUE THREAD

**Issue by jinmallll** [experiencor/basic-yolo-keras#38]
center_w = (obj['xmax'] - obj['xmin']) / (float(self.config['IMAGE_W']) / self.config['GRID_W']) # unit: grid cell center_h = (obj['ymax'] - obj['ymin']) / (float(self.config['IMAGE_W']) / self.config['GRID_W']) # unit: grid cell

Is there any effect when the image ratio is not 1:1?

**Comment by experiencor** [comment]
@jinmallll This is a bug. It should be IMAGE_H and GRID_H in the second line. In principle, the code should work with the ratio other than 1:1. However, I have not tested. The code may break here and there.

**Comment by jinmallll** [comment]
OK. Thank you very much.
