### ISSUE TITLE
Error in parse_annotation

### ISSUE THREAD

**Issue by taojiastanford** [experiencor/basic-yolo-keras#40]
Dear experiencor,
When I run the code in the notebook "Yolo Step-by-Step", I found the following error executing the 10th command (Image attached):
![image](https://user-images.githubusercontent.com/9204976/32701319-252a12ce-c788-11e7-9eb7-47a2df9b8546.png)

> File "<string>", line unknown ParseError: not well-formed (invalid token): line 1, column 0

I was using the pictures and annotations downloaded from COCO network, and I put them in a backup hard drive (because the size of files is huge for my computer...).

Thank you! Also thanks for your code and detailed tutorial!

**Comment by experiencor** [comment]
@taojiastanford I think the error is caused by improperly formatted annotation. Have you converted COCO annotation format to VOC format? This is the script to do so: https://gist.github.com/chicham/6ed3842d0d2014987186#file-coco2pascal-py.
