### ISSUE TITLE
Are you reversing the image channels?

### ISSUE THREAD

**Issue by bshao001** [experiencor/basic-yolo-keras#44]
I am not sure I understand this correctly. But I see you have the similar lines in both training data preprocessing and prediction:

    input_image = image[:, :, ::-1]

Are you reversing the RGB channels of the image(s)? If so, why is that?

Sorry to keep bothering you. Thank you so much for the help!

**Comment by experiencor** [comment]
@bshao001 You are welcome. The reason is that I use OPENCV to read in the image. The default order of opencv is BGR (https://docs.opencv.org/3.0-beta/modules/imgcodecs/doc/reading_and_writing_images.html). So I need to switch B and R using that line.

**Comment by bshao001** [comment]
@experiencor Thank you. I just noticed that myself before checking your answer.
