### ISSUE TITLE
Model for hand detection

### ISSUE THREAD

**Issue by Zumbalamambo** [experiencor/basic-yolo-keras#47]
can you please share the model for hand detection?

**Comment by experiencor** [comment]
@Zumbalamambo I don't have the model for hand detection with me as the picture was provided by a user of this repo. You may it yourself using the data from here: http://cvrr.ucsd.edu/vivachallenge/index.php/hands/hand-detection/.

**Comment by MyraBaba** [comment]
I have hands from different angels.. How many training image I need ? 10 ? 100 ?  1000 . or 10000

how many training image make sense _
