### ISSUE TITLE
raccoon training problem

### ISSUE THREAD

**Issue by z5254215560** [experiencor/basic-yolo-keras#49]
hey, i am trying to test the raccoon  dataset, i clone your dataset and model and code here, i got the error that i can't understand. i am very new in object detection field , could you plz help me up?
```
Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 136, in _main_
    debug              = config['train']['debug'])
  File "/home/e44041034/basic-yolo-keras/frontend.py", line 445, in train
    max_queue_size   = 8)
  File "/home/e44041034/basic-yolo-keras/yolokeras/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/e44041034/basic-yolo-keras/yolokeras/local/lib/python2.7/site-packages/keras/engine/training.py", line 2083, in fit_generator
    generator_output = next(output_generator)
  File "/home/e44041034/basic-yolo-keras/yolokeras/local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 553, in get
    raise StopIteration(e)
StopIteration: 'NoneType' object has no attribute 'shape'
```

```json

    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "/home/e44041034/basic-yolo-keras/raccoon_dataset/images/",
        "train_annot_folder":   "/home/e44041034/basic-yolo-keras/raccoon_dataset/annotations/",

        "train_times":          10,
        "pretrained_weights":   "",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_batches":       250,

        "object_scale":         5.0,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_raccoon.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}
```

**Comment by kabrau** [comment]
I had this problem, I think is same.

The problem is because the image name is .JPG and into XML the image name is .PNG.
You fix this with a replace when load images (tensorflow, MacGyver) or adjusts image names or adjusts xml files.

**Comment by experiencor** [comment]
@kabrau is right. You can just use my fork of that dataset at https://github.com/experiencor/raccoon_dataset. I fixed this problem in my fork.

**Comment by z5254215560** [comment]
think your guys

**Comment by bhavindhedhi** [comment]
I have the same problem with my own dataset and i have same names in both xml and image file name what do i do

**Comment by experiencor** [comment]
@bhavindhedhi I suggest you use the notebook ```Yolo Step-by-Step.ipynb``` to debug. It's very hard to comment without any details.

**Comment by kabrau** [comment]
@bhavindhedhi - You may be reading from the wrong folder, or you may be missing some image.

**Comment by bhavindhedhi** [comment]
quick update, I solved the error by changing following in the train.py file:
from:
`if os.path.exists(config['valid']['valid_annot_folder']):`
to:
`if os.path.exists(r"config['valid']['valid_annot_folder']"):`

and
from:
`if os.path.exists(config['train']['pretrained_weights']):`
to:
`if os.path.exists(r"config['train']['pretrained_weights']"):`

**Comment by experiencor** [comment]
@bhavindhedhi This trick works but is not intended. ```os.path.exists(r"config['train']['pretrained_weights']")``` is almost always false.
