### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by AhmedAAkl** [experiencor/basic-yolo-keras#50]
first of all, Good job 
 I want to train this model from scratch. (e.g. tiny yolo)
for real time problems
when i tried to turn the train.py file, an error appears that it can't open the weights file 
" OSError: Unable to open file (Unable to open file: name = 'full_yolo_features.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0) "
I didn't want to load it
i want to load the model architecture then train it in my own dataset

Thanks in advance.

**Comment by kabrau** [comment]
H

In config.json you need to clear the "pretrained_weights":   "",
or
 if you would like start with weigthts, you need download pretrained features of full yolo at:
https://1drv.ms/f/s!ApLdDEW3ut5fec2OzK4S4RpT-SU
and save in basic-yolo-keras folder root

**Comment by experiencor** [comment]
@AhmedAAkl @kabrau is right. You need to download and put the pretrained weights of the TinyYolo backend in the root folder. The backend must be pre-trained, otherwise the network would not converge. It's very difficult to train an object detection model from scratch.

**Comment by AhmedAAkl** [comment]
@kabrau thanks for response. but, i cleared the "pretrained_weights". and also i didn't work.
the problem appears when backend.py module tries to load_weights() 
        self.feature_extractor.load_weights(TINY_YOLO_FEATURE_PATH)
i didn't find the specified weights file.
@experiencor  you are right the backend will load the pretrained weights.
i want to train this model to detect the traffic signs and classify them so, i want to train the tiny yolo from scratch.
thanks

**Comment by kabrau** [comment]
Hi @AhmedAAkl, 
Is the dataset of the traffic signs public? 
If yes, can you send me url ? 
Tks

**Comment by AhmedAAkl** [comment]
@kabrau  unfortunately, it is not public. ( traffic sign detection)
all tutorial shows that the developer make it by him self.
but, sign recognition is available. try the german traffic signs dataset. it is the popular.
