### ISSUE TITLE
Retraining the model

### ISSUE THREAD

**Issue by bhanu223** [experiencor/basic-yolo-keras#51]
Can I retrain the model by loading my already trained weights? Or I should add my new images and train the entire image set again?

**Comment by experiencor** [comment]
@bhanu223 If you have new image, I suggest you load the weights trained on previous images and train on the combined dataset (old + new) again. You can use the "pretrained_weights" setting in config.json to load the previously trained weights.

**Comment by bhanu223** [comment]
cool. Thanks for the suggestion.
