### ISSUE TITLE
Mismatched tensor shapes

### ISSUE THREAD

**Issue by alanjschoen** [experiencor/basic-yolo-keras#52]
Thanks a lot for making this repo.  I have been using it with my own dataset using python3.  I have resolved a few version compatibility issues, but now I'm stuck on an issue which I don't think is related to the python version or library versions.

I'm trying to train YOLO on my own dataset with 54 classes, and I'm getting the error:
```
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    _main_(args)
  File "train.py", line 131, in _main_
    debug              = config['train']['debug'])
  File "/home/aschoen/git/basic-yolo-keras/frontend.py", line 444, in train
    max_queue_size   = 8)
  File "/home/aschoen/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/aschoen/.local/lib/python3.5/site-packages/keras/engine/training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "/home/aschoen/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "/home/aschoen/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/home/aschoen/.local/lib/python3.5/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected lambda_2 to have shape (None, 13, 13, 5, 59) but got array with shape (16, 13, 13, 5, 6)
```
I'm getting the same error regardless of whether I use the train.py script or the Yolo Step-by-Step notebook.

I notice that the raccoon example has one category, so the last dimension of each tensor seems to correspond to number of classes + 5.  So I assume this problem is arising because some part of the train function does not know the correct number of classes.  

I set the LABELS variable, and so it seems that the model is getting the correct output dimension via `output = Reshape((GRID_H, GRID_W, BOX, 4 + 1 + CLASS))(x)`, so I think the model is the correct size and it's some other operand that has the wrong size, but it's hard for me to tell where the error is coming from, so I haven't been able to tell what the other tensor is so I can fix the size.

**Comment by alanjschoen** [comment]
I have a small update.  I found this line in the __getitem__ class of the BatchGenerator class:
```
y_batch = np.zeros((r_bound - l_bound, self.config['GRID_H'],  self.config['GRID_W'], self.config['BOX'], 4+1+1))
```
And I think this means that the number of classes in `y` is fixed to 1

**Comment by experiencor** [comment]
@alanjschoen I use 4+1+1 but not 4+1+CLASS as we only need to pass the index of the object, instead of the one-hot encoding. Says, to signal that the class of the object is the fifth class, I only need to pass index 4, instead of vector [0, 0, 0, 0, 1]. It saves some memory transfer between CPU and GPU this way.

You may further notice that I use ```tf.nn.sparse_softmax_cross_entropy_with_logits``` (line 216 in frontend.py) to compute the classification loss. I only need the index of the class, not the full one-hot encoding.

Another user has this same problem (https://github.com/experiencor/basic-yolo-keras/issues/43). It turns out that Keras > 2.0.8 does not allow this mismatched shape. He installed Keras 2.0.8 and the issue disappear. You may give it a try.

**Comment by alanjschoen** [comment]
I just want to confirm that I changed my keras version and that fixed the problem.
