### ISSUE TITLE
multiple class training

### ISSUE THREAD

**Issue by Isabelliu** [experiencor/basic-yolo-keras#53]
Dear experiencor,
thanks for your great job.
If i want to train the traffic signs. and there are different shapes of the traffic signs. such as circle,triangle.
should i train them as one class or multiple classes?
and how can i train on multiple classes?
thanks for your time!

**Comment by experiencor** [comment]
Hi @Isabelliu If the objects are that different, I suggest you use different classes for them. Training on multiple classes is a breeze as my implementation is meant to be used with any number of class. One caution though. You need to use **Keras less than equal to 2.0.8** as later Keras will complain about mismatched shapes.

**Comment by alanjschoen** [comment]
Thanks for your feedback!  I was having compatibility issues with 2.0.3 so I upgraded to 2.1.1.  I will try out 2.0.8.

**Comment by Isabelliu** [comment]
thank you very much. I will try it out soon.

**Comment by experiencor** [comment]
I changed preprocessing.py to fix the size mismatched problem. So now it transfers the full one hot encoding from CPU to GPU and can run on any version of Keras.
