### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by alanjschoen** [experiencor/basic-yolo-keras#54]
Thanks again for creating this repo.  I think there is a real need for a package like this that makes it easy to configure and train a YOLO model in python.  I have been working with this repo for a little while, and I have had a couple of problems related to the keras version.  So I would appreciate if you could add a requirements.txt file showing what library versions you used.

**Comment by experiencor** [comment]
@alanjschoen This is a very good suggestion. I will add the requirements.txt in a couple of days.
