### ISSUE TITLE
Yolo step by step: weight_reader

### ISSUE THREAD

**Issue by JaspervDalen** [experiencor/basic-yolo-keras#59]
I tried to use your notebook and loading the weights gave the following error:
`ValueError                                Traceback (most recent call last)
<ipython-input-9-16ee56ba09e1> in <module>()
     20         bias   = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[1].shape))
     21         kernel = weight_reader.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
---> 22         kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
     23         kernel = kernel.transpose([2,3,1,0])
     24         conv_layer.set_weights([kernel, bias])

ValueError: cannot reshape array of size 127700 into shape (425,1024,1,1)`

I tried to redownload the weights from the provided link but the error stays the same. Do I have the wrong weights or is there another problem?

**Comment by experiencor** [comment]
@JaspervDalen Thanks. It's an error. The notebook uses the weight from here https://pjreddie.com/media/files/yolo.weights.

**Comment by JaspervDalen** [comment]
and the weights_coco.h5? Can I find them somewhere?

**Comment by experiencor** [comment]
I didn't upload it. What backend would you like? I can send you.

**Comment by JaspervDalen** [comment]
At them moment I am just trying to run your notebook (so full yolo backend). This notebook contains a line that loads weights. And I think that they do not exist yet as no checkpoint is made right?

**Comment by experiencor** [comment]
Yes, it's just a checkpoint during training. The notebook is able to load weights trained using Darknet code. You can just load Darknet weghts then model.save to create the weight in keras format.

**Comment by JaspervDalen** [comment]
thanks!
