### ISSUE TITLE
Error repeating training on raccoon dataset

### ISSUE THREAD

**Issue by numensgh** [experiencor/basic-yolo-keras#60]
Hi and thank you for sharing your code. I am trying to retrain the model on raccoon dataset but I run into the following errors when  python train.py -c config.json

Using TensorFlow backend.
Seen labels:	{'raccoon': 217}
Given labels:	[u'raccoon']
Overlap labels:	set(['raccoon'])

--------------------------------
2017-11-29 15:49:30.412746: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
(13, 13)
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
input_1 (InputLayer)             (None, 416, 416, 3)   0                                            
____________________________________________________________________________________________________
model_1 (Model)                  (None, 13, 13, 1024)  50547936    input_1[0][0]                    
____________________________________________________________________________________________________
conv_23 (Conv2D)                 (None, 13, 13, 30)    30750       model_1[1][0]                    
____________________________________________________________________________________________________
reshape_1 (Reshape)              (None, 13, 13, 5, 6)  0           conv_23[0][0]                    
____________________________________________________________________________________________________
input_2 (InputLayer)             (None, 1, 1, 1, 10, 4 0                                            
____________________________________________________________________________________________________
lambda_2 (Lambda)                (None, 13, 13, 5, 6)  0           reshape_1[0][0]                  
                                                                   input_2[0][0]                    
====================================================================================================
Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672
____________________________________________________________________________________________________
Loading pre-trained weights in full_yolo_raccoon.h5
Epoch 1/3
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    _main_(args)
  File "train.py", line 138, in _main_
    debug              = config['train']['debug'])
  File "/home/andrea/Keras/basic-yolo-keras/frontend.py", line 446, in train
    max_queue_size   = 8)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 510, in get
    raise StopIteration(e)
StopIteration: 'NoneType' object has no attribute 'shape'

Could you please point on how to solve this issue?

**Comment by experiencor** [comment]
@numensgh This error means that the generator failed to read the images with images specified in the corresponding xml annotation file. I guess that you are using the original Raccoon dataset. I suggest you use the corrected one at https://github.com/experiencor/raccoon_dataset.

**Comment by numensgh** [comment]
Indeed, the path specified in the xml annotation files were pointing to the wrong folder. 
Thank you very much
