### ISSUE TITLE
cannot import name 'Sequence'

### ISSUE THREAD

**Issue by jhasuman** [experiencor/basic-yolo-keras#62]
Hi, I am using AWS, ubuntu os. Getting this error "Cannot import name 'Sequence'" 
Please let me know, what am I missing? 

![image](https://user-images.githubusercontent.com/17616710/33397456-ae4032cc-d571-11e7-8d6d-129700ce002e.png)

**Comment by experiencor** [comment]
@jhasuman Please use Keras >= 2.0.8. You will have this error with older version of Keras.

**Comment by jhasuman** [comment]
Hi Thanks!! I have updated my Keras version!! But now I am getting 

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Detailed error**

`TypeError                                 Traceback (most recent call last)
~/basic-yolo-keras/train.py in <module>()
    138 if __name__ == '__main__':
    139     args = argparser.parse_args()
--> 140     _main_(args)

~/basic-yolo-keras/train.py in _main_(args)
    107                 labels              = config['model']['labels'],
    108                 max_box_per_image   = config['model']['max_box_per_image'],
--> 109                 anchors             = config['model']['anchors'])
    110 
    111     ###############################

~/basic-yolo-keras/frontend.py in __init__(self, architecture, input_size, labels, max_box_per_image, anchors)
     46             self.feature_extractor = MobileNetFeature(self.input_size)
     47         elif architecture == 'Full Yolo':
---> 48             self.feature_extractor = FullYoloFeature(self.input_size)
     49         elif architecture == 'Tiny Yolo':
     50             self.feature_extractor = TinyYoloFeature(self.input_size)

~/basic-yolo-keras/backend.py in __init__(self, input_size)
    157         skip_connection = Lambda(space_to_depth_x2)(skip_connection)
    158 
--> 159         x = concatenate([skip_connection, x])
    160 
    161         # Layer 22

/usr/local/lib/python3.5/dist-packages/keras/layers/merge.py in concatenate(inputs, axis, **kwargs)
    625         A tensor, the concatenation of the inputs alongside axis `axis`.
    626     """
--> 627     return Concatenate(axis=axis, **kwargs)(inputs)
    628 
    629 

/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    601 
    602             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 603             output = self.call(inputs, **kwargs)
    604             output_mask = self.compute_mask(inputs, previous_mask)
    605 

/usr/local/lib/python3.5/dist-packages/keras/layers/merge.py in call(self, inputs)
    345             raise ValueError('A `Concatenate` layer should be called '
    346                              'on a list of inputs.')
--> 347         return K.concatenate(inputs, axis=self.axis)
    348 
    349     def compute_output_shape(self, input_shape):

/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py in concatenate(tensors, axis)
   1761         return tf.sparse_concat(axis, tensors)
   1762     else:
-> 1763         return tf.concat([to_dense(x) for x in tensors], axis)
   1764 
   1765 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py in concat(concat_dim, values, name)
   1073       ops.convert_to_tensor(concat_dim,
   1074                             name="concat_dim",
-> 1075                             dtype=dtypes.int32).get_shape(
   1076                             ).assert_is_compatible_with(tensor_shape.scalar())
   1077       return identity(values[0], name=scope)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    667 
    668         if ret is None:
--> 669           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    670 
    671         if ret is NotImplemented:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    174                                          as_ref=False):
    175   _ = as_ref
--> 176   return constant(v, dtype=dtype, name=name)
    177 
    178 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    163   tensor_value = attr_value_pb2.AttrValue()
    164   tensor_value.tensor.CopyFrom(
--> 165       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    166   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    167   const_tensor = g.create_op(

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    365       nparray = np.empty(shape, dtype=np_dt)
    366     else:
--> 367       _AssertCompatible(values, dtype)
    368       nparray = np.array(values, dtype=np_dt)
    369       # check to them.

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py in _AssertCompatible(values, dtype)
    300     else:
    301       raise TypeError("Expected %s, got %s of type '%s' instead." %
--> 302                       (dtype.name, repr(mismatch), type(mismatch).__name__))`

**Comment by jhasuman** [comment]
Now this error!! Can anyone please help

![image](https://user-images.githubusercontent.com/17616710/33552102-ba3c3b06-d919-11e7-906f-8efd1d2029ae.png)

**Comment by experiencor** [comment]
@jhasuman You forgot to feed the config file to the train.py script. Please read the instruction carefully to avoid these issues.

**Comment by jhasuman** [comment]
ohh!! Sorry!! But now I am getting the error of import 

ImportError: `load_weights` requires h5py

![image](https://user-images.githubusercontent.com/17616710/33564417-75c6e044-d940-11e7-85bd-ee012cf80579.png)

![image](https://user-images.githubusercontent.com/17616710/33564460-89f11a08-d940-11e7-8438-cf419c14a7ee.png)


And in jupyter notebook 

Getting the value error. 

![image](https://user-images.githubusercontent.com/17616710/33564510-aeba4abc-d940-11e7-9232-39a26e89fe57.png)

Please help

**Comment by experiencor** [comment]
@jhasuman You need to install h5py. Keras requires h5py to read the weight file. What is the weight file that you use? Please read the instruction at the top of the notebook carefully.

**Comment by jhasuman** [comment]
Hi Thank You so much!! But I believe this is the last issue

![image](https://user-images.githubusercontent.com/17616710/33681379-55a4e472-daea-11e7-9194-01afae461201.png)

Please help!! It seems I am making some mistake.

**Comment by experiencor** [comment]
@jhasuman You should end ```train_annot_folder``` with the back slash (/).

**Comment by jhasuman** [comment]
Hi, Thank You so much!!

I know I am asking some basic questions but that's the only way I could learn. 
I actually didn't understand data conversion part from COCO to VOC and why ??
-Run this script to convert annotations in COCO format to VOC format 
https://gist.github.com/chicham/6ed3842d0d2014987186#file-coco2pascal-py 

Now I am getting this error, I believe this is because of I have not converted COCO format. (What I did, I downloaded from website and arrange the folder in the way of train_image, train_annot, vali_image and vali_annot

This is the screenshot!!

![image](https://user-images.githubusercontent.com/17616710/33701823-9be33fcc-db46-11e7-9b67-d33aa3b79ce3.png)

**Comment by experiencor** [comment]
@jhasuman I guess you use python 3. You can change ```range(len(config['ANCHORS'])/2)``` to ```range(len(config['ANCHORS'])//2)```.

**Comment by jhasuman** [comment]
Yes, I am using python 3. After changing also there is no luck ): 

![image](https://user-images.githubusercontent.com/17616710/33759692-4356f27a-dc29-11e7-8557-515296728d3e.png)

**Comment by experiencor** [comment]
@jhasuman You can use ```range(int(len(config['ANCHORS'])//2))```.

**Comment by nacgarg** [comment]
@jhasuman How did you fix the `TypeError: Expected int32, got list containing Tensors of type '_Message' instead.` issue?
