### ISSUE TITLE
Issue in training on Raccoon dataset

### ISSUE THREAD

**Issue by khiemntu** [experiencor/basic-yolo-keras#63]
Hi. I have a problem when training with Raccoon dataset. I dont know why it always stop when I run after a few minutes. I re-train many time but the result no change.

This is my config:
```
{
    "model" : {
        "architecture":         "Tiny Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "../raccoon_dataset/train/images/",
        "train_annot_folder":   "../raccoon_dataset/train/annotations/",     
          
        "train_times":          10,
        "pretrained_weights":   "",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        0,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "tiny_yolo_raccoon_save.h5",
        "debug":                false
    },

    "valid": {
        "valid_image_folder":   "../raccoon_dataset/valid/images/",
        "valid_annot_folder":   "../raccoon_dataset/valid/annotations/",
        "valid_times":          1
    }
}

```

```
Epoch 1/50
 10/100 [==>...........................] - ETA: 1:11 - loss: 11.5398Epoch 00001: val_loss improved from inf to 5.79008, saving model to tiny_yolo_raccoon_save.h5
 10/100 [==>...........................] - ETA: 1:22 - loss: 11.5398 - val_loss: 0.0000e+00Epoch 2/50
 10/100 [==>...........................] - ETA: 44s - loss: 9.3070Epoch 00002: val_loss improved from 5.79008 to 5.75633, saving model to tiny_yolo_raccoon_save.h5
 10/100 [==>...........................] - ETA: 55s - loss: 9.3070 - val_loss: 0.0000e+00Epoch 3/50
 10/100 [==>...........................] - ETA: 44s - loss: 6.9476Epoch 00003: val_loss improved from 5.75633 to 4.91244, saving model to tiny_yolo_raccoon_save.h5
 10/100 [==>...........................] - ETA: 55s - loss: 6.9476 - val_loss: 0.0000e+00Epoch 4/50
 10/100 [==>...........................] - ETA: 44s - loss: 4.7331Epoch 00004: val_loss improved from 4.91244 to 4.88484, saving model to tiny_yolo_raccoon_save.h5
 10/100 [==>...........................] - ETA: 55s - loss: 4.7331 - val_loss: 0.0000e+00Epoch 5/50
 10/100 [==>...........................] - ETA: 44s - loss: 3.8645Epoch 00005: val_loss did not improve
 10/100 [==>...........................] - ETA: 53s - loss: 3.8645 - val_loss: 0.0000e+00Epoch 6/50
 10/100 [==>...........................] - ETA: 44s - loss: 3.8343Epoch 00006: val_loss did not improve
 10/100 [==>...........................] - ETA: 52s - loss: 3.8343 - val_loss: 0.0000e+00Epoch 7/50
 10/100 [==>...........................] - ETA: 44s - loss: 3.4981Epoch 00007: val_loss did not improve
 10/100 [==>...........................] - ETA: 53s - loss: 3.4981 - val_loss: 0.0000e+00Epoch 00007: early stopping
```

It train in to few minute ???  Too fast !!!!!. Are there something wrong in here, the val_loss is 0.0000+e00, but there are no box found when I predict ? And I have question, why the progress bar only run to 10/100 each epoch ? I never seen it run to 100/100 ? Thank you so much, hope anyone reply, I tried many many times but the result seem not good :(

**Comment by experiencor** [comment]
@khiemntu I tried your config. It ran fine with the latest code. I didn't have your 2 problems.

Are you using the latest code and what is the version of Keras? I suggest you use Keras >= 2.0.8.

P/S: from my experience, it's tough to get Tiny Yolo to detect raccoon. You need to play with the 4 scales. The Full Yolo will work out of the box though.

**Comment by khiemntu** [comment]
using keras 2.1.1 and the lastest code of you. But it run to 10/100 and go to next epoch. Val_loss after the first epoch (10/100) alway 0.0000e+00 :(

**Comment by khiemntu** [comment]
@experiencor I think it run to 10/100 because number_of_train_image / batch_size = 160/16 = 10
I set batch size 8 and it run to 20/200, because 160 / 8 = 20. Are there any involve with **train_batch** from BatchGenerator ?

**Comment by khiemntu** [comment]
@experiencor I found the problem at file preprocessing.py ~ Line 76
 `self.anchors = [BoundBox(0, 0, config['ANCHORS'][2*i], config['ANCHORS'][2*i+1]) for i in range(int(len(config['ANCHORS'])/2))]`
I must add integer parse for len(..)/2 because float result make wrong val_loss (0.0000e+00) and progress counting!

**Comment by Ovy1** [comment]
@khiemntu were you able to resolve the TypeError: 'float' object cannot be interpreted as an integer by using **int** in for i in range(int(len(config['ANCHORS'])/2))] ? am experiencing a similar issue 

---> 78         self.anchors = [BoundBox(0, 0, config['ANCHORS'][2*i], config['ANCHORS'][2*i+1]) for i in range(len(config['ANCHORS'])/2)]
     79 
     80         ### augmentors by https://github.com/aleju/imgaug

TypeError: 'float' object cannot be interpreted as an integer

i tried with int() the same error

**Comment by Ovy1** [comment]
@khiemntu no worries it's working now, i was able to fix it.

**Comment by khiemntu** [comment]
@Ovy1 This issue occur when I run with Python3.5. what python version are you using ?

**Comment by Ovy1** [comment]
@khiemntu same Python3.5. no wonder it failed. 
Hey am currently battling the below error msg
 **NameError: name 'xrange' is not defined**

both in **frontend.py and utils.py**  because 'xrange has no value to run the loop against. 
CODE:
**** suppress non-maximal boxes


            for i in **xrange**(len(sorted_indices)):
                index_i = sorted_indices[i]

did you ran into this issue by any chance ?

**Comment by khiemntu** [comment]
@Ovy1 I am work fine without your error on python3.5 :)

**Comment by experiencor** [comment]
@khiemntu Have you fixed this issue?

**Comment by yaibait** [comment]
I got same error , trainning very fast

**Comment by experiencor** [comment]
@yaibait Can you be more specific? And what are your Keras and this code versions?

**Comment by yaibait** [comment]
@experiencor  I am using Keras '2.0.9' , and my problem like @khiemntu describe 
I am running your script on python 3 and change 
- preprocessing.py ~ Line 76 config['ANCHORS'])/2) to config['ANCHORS'])//2)
- xrange to range

**Comment by experiencor** [comment]
I made these change but still couldn't reproduce the error. You may want to try python 2.
