### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Ovy1** [experiencor/basic-yolo-keras#64]
Hi experiencor, i need your help with preprocessing.py line ---> 76 
'float' object cannot be interpreted as an integer

line ---> 76         self.anchors = [BoundBox(0, 0, config['ANCHORS'][2*i], config['ANCHORS'][2*i+1]) for i in range (len(config['ANCHORS'])/2))]

i even tried an int     "for i in range(**int**(len(config['ANCHORS'])/2))]" same error.

see  Trace below 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-3b1d916fe1d2> in <module>()
----> 1 batches = BatchGenerator(all_imgs, generator_config)

..../preprocessing.py in __init__(self, images, config, shuffle, jitter, norm)
     74 
     75         self.counter = 0
---> 76         self.anchors = [BoundBox(0, 0, config['ANCHORS'][2*i], config['ANCHORS'][2*i+1]) for i in range(int(len(config['ANCHORS'])/2))]
     77 
     78         ### augmentors by https://github.com/aleju/imgaug

TypeError: 'float' object cannot be interpreted as an integer

thanks for your help in advance.

**Comment by Ovy1** [comment]
@experiencor no worries it's working now, i was able to fix it.

**Comment by prathaprpm** [comment]
@Ovy1 Can you please post the solution. I am facing same issue.
I tried "for i in range(len(config['ANCHORS'])//2)" same error is repeating

**Comment by experiencor** [comment]
@Ovy1 Please use the latest code. I fixed this error once for all by changing to ```range(int(len(config['ANCHORS'])//2))```.

**Comment by prathaprpm** [comment]
Thank you
