### ISSUE TITLE
'xrange' is not defined when making prediction.  'xrange' in utils.py 

### ISSUE THREAD

**Issue by Ovy1** [experiencor/basic-yolo-keras#65]
Hi experiencor, please i need your help xrange in utils.py has no value to loop against. i even tried function range () i got the same error msg

NameError                                 Traceback (most recent call last)
<ipython-input-40-b066dee977e1> in <module>()
     16                       nms_threshold=NMS_THRESHOLD,
     17                       anchors=ANCHORS,
---> 18                       nb_class=CLASS)
     19 image = draw_boxes(image, boxes, labels=LABELS)
     20 

......./utils.py in decode_netout(netout, obj_threshold, nms_threshold, anchors, nb_class)
    135         sorted_indices = list(reversed(np.argsort([box.classes[c] for box in boxes])))
    136 
**--> 137         **for i in xrange(len(sorted_indices)):**
    138             index_i = sorted_indices[i]**
    
NameError: name 'xrange' is not defined

**Comment by CGCooke** [comment]
If you are running the code with Python3, then I think you need to use range instead of xrange,
http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#integer-division

**Comment by khiemntu** [comment]
@Ovy1 There are no error like you when I run on python 3.5.

**Comment by experiencor** [comment]
I really should have included python = 2.7 in the readme.

**Comment by Ovy1** [comment]
@CGCooke @experiencor thanks guys.
