### ISSUE TITLE
small or tiny object detection

### ISSUE THREAD

**Issue by Isabelliu** [experiencor/basic-yolo-keras#66]
Hi,experiencor,
I want to detect some objects that is very small compared to the whole image. 
eg: image size 2000    2500  object size: 20   25 
Do you think if the YOLOV2 model can handle this? Which parameters should I change for this task?
Should I set the anchors  smaller?
Or if the Yolov2 is not good at tiny object detection? DO you know is there any other models good at it ?
Thank you for your time.

**Comment by experiencor** [comment]
Yes. You should adjust the size of the anchors to work best with your dataset. The rule is that the sizes of the anchors should be the prevalent sizes of the bounding boxes in your dataset. After that, I think YOLOv2 will work fine with your dataset.

**Comment by Isabelliu** [comment]
thank  you, I will try.

**Comment by jjjjohnson** [comment]
Hi @Isabelliu Have you tried small object? How is that going after setting the anchors?

**Comment by experiencor** [comment]
@jjjjohnson Sorry for the late reply as I was on vacation. You can now try gen_anchors.py to generate the custom anchor sizes to suit your dataset (small objects).

**Comment by jjjjohnson** [comment]
@experiencor Thanks. Yes I tried that. It generated some suggested anchors but YOLO still performed poorly. Maybe I need better quality training data...
