### ISSUE TITLE
About anchor point va 4 scales

### ISSUE THREAD

**Issue by khiemntu** [experiencor/basic-yolo-keras#67]
Do I need re-calculate anchor point when training new dataset ?? Or just using the anchor in this implement for all dataset ? 
Second question, how does 4 scales effect in training ? What happen when I increase or decrease `object_scales` or `coord_scale` more than twices ?

**Comment by experiencor** [comment]
You can gain a bit accuracy if you to re-calculate the anchors. The sizes of the anchors should be the prevalent sizes of the bounding boxes in the dataset.

Please read ```2. Edit the configuration file``` in the README.md for clarification of those 4 parameters. For more details, you can refer to the YOLO paper https://arxiv.org/abs/1506.02640.
