### ISSUE TITLE
It would be very kind if you could provide a license with your code

### ISSUE THREAD

**Issue by nylocx** [experiencor/basic-yolo-keras#68]
As the heading states. A license would be a nice to have and could help others to use this code in their projects and could also help to boost the contributions to the project.

**Comment by experiencor** [comment]
Licence added. Basically, you are free to use the code in whatever way you like.

**Comment by nylocx** [comment]
Thanks a lot, for this and for the good work creating this project. This will make my job a bit easier to migrate from the darknet yolo implementation to a keras/tensorflow one.
