### ISSUE TITLE
Detect similar but not the same objects

### ISSUE THREAD

**Issue by usatenko** [experiencor/basic-yolo-keras#72]
Hi, thank you for great work.
I write a detector for bottles from the top view, all bottles are similar and differ only slightly.
One bottle type is open (without cap) and the other is closed (with cap).
Considering I can prepare any training dataset of images, which bottle size in percentage from the whole image should I choose to have these similar objects detected as different object types?

**Comment by experiencor** [comment]
I think that relative size to bottle to image does not matter for YOLO. It's fine as long as they are visually different (like the cap).

**Comment by usatenko** [comment]
Thank you very much for the answer.
