### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by JaspervDalen** [experiencor/basic-yolo-keras#74]
I tried to do multi GPU training and i get errors at the end of epochs. This is most of the time a cannot serialize _io.textiowrapper object error. All of the errors happen in the deepcopy called in the callbacks/on epochs end from keras. In one of the issues I read you had it working with multiple gpu's. Is there something special you have to do to make it work?

**Comment by experiencor** [comment]
@JaspervDalen Can you provide more details like how you do multi-GPU training? I use https://github.com/rossumai/keras-multi-gpu and don't run into this problem.

**Comment by JaspervDalen** [comment]
I used this as an example:
https://www.pyimagesearch.com/2017/10/30/how-to-multi-gpu-training-with-keras-python-and-deep-learning/

so I build the model on the cpu (with tf.device("/cpu:0"): ) and use model = multi_gpu_model(model, gpus=2) before starting training

I will have a look at your link, thanks!

**Comment by experiencor** [comment]
Did you run successfully? Mind to share the code :).

**Comment by JaspervDalen** [comment]
Not yet, had some other stuff to do. If i get it working I will share some results
