### ISSUE TITLE
Anchor automatic calculation

### ISSUE THREAD

**Issue by usatenko** [experiencor/basic-yolo-keras#75]
Hi,
as I understand anchors should be calculated based on the certain dataset? If so, is there a way to calculate them automatically. I have found this method: https://github.com/leetenki/YOLOv2/blob/master/dimension_cluster.py#L1 however, it generates slightly different values.

**Comment by experiencor** [comment]
@usatenko slightly different from what values? The values should be different for different datasets.

**Comment by dhruvp** [comment]
@usatenko that method outputs centroid bounding box width + height multiplied by the grid size. In @experiencor 's implementation, the anchor size units are fractions of the grid size. So you'll probably need to convert them into the right units.

**Comment by usatenko** [comment]
OK, anchor automatic calculation, I took the code from another yolo implementation, adopted slightly and I would like you to append to your code.
Here is the pull request: https://github.com/experiencor/basic-yolo-keras/pull/110

**Comment by vitasiku** [comment]
@usatenko, thanks. When I run the gen_anchors.py file on my dataset, I get 
![image](https://user-images.githubusercontent.com/4680164/34603458-0c91a1c0-f215-11e7-8209-058a86d0035f.png)

Here is, the content of gen_anchors.py(renamed to .txt to allow attaching) I got from the above pull request
[gen_anchors.py.txt](https://github.com/experiencor/basic-yolo-keras/files/1606129/gen_anchors.py.txt)

**Comment by vitasiku** [comment]
Solved it. Issue was that the code was written for python2 and I am running python3.6 where this code block `map(float,(w,h))` returns a map object instead of a tuple of float values as intended. Hence, calling `centroids.shape` is one-dimensional.

**Comment by vitasiku** [comment]
However on the Red Blood Cells dataset, the anchors generated are `[0.2169299451,0.2305288462,0.2439903846,0.2892839069,0.2566818774,0.2439496415,0.2780612245,0.2114894035,0.3000733377,0.2739977184]` instead of `[0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828]` which were supplied in the jupyter notebook. Why are the values different?

**Comment by ttorkar** [comment]
Can you run train two models with each of the anchors to see which performs better? I assume that the former is the real fit but it would be good to verify. Can you check the other configs to see if the latter anchor points match?  It could be that the latter is just a generic set.

**Comment by vitasiku** [comment]
@ttorkar will try and let you know.

**Comment by MrMey** [comment]
Hi, looking at gen_anchors I see that piece of code (below). Could someone explain me why it is divided by 32? I would expect something like 13 (number of cells).
Thanks.


Line 110:
train_imgs, train_labels = parse_annotation(config['train']['train_annot_folder'],
                                                config['train']['train_image_folder'],
                                                config['model']['labels'])

grid_w = config['model']['input_size']/**32**
grid_h = config['model']['input_size']/**32**

**Comment by experiencor** [comment]
@MrMey 32 is the factor that FullYolo and TinyYolo backends scale down an image. If your input_size is 416, the grid size at the end of these two backends is 416/32=13. This factor also works with InceptionV3, ResNet, and VGG, but not with SqueezeNet backend. I should have used some kind of enum here.
