### ISSUE TITLE
Settingup callbacks

### ISSUE THREAD

**Issue by prathaprpm** [experiencor/basic-yolo-keras#80]
Hi,
I'm still new to python and deep learning. I am trying to use Yolo Step-by-Step.ipynb to do my first object detection with bounding box on a video.
I am getting error for the following line
model.load_weights('weights_coco.h5')

error:
OSError: Unable to open file (unable to open file: name = 'weights_coco.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I understand that it looking for file weights_coco.h5 and is unable to find it. I didn't understand what is weights_coco.h5 where is it generated. There is no mention of it in the instructions at the beginning.
Please help me.

**Comment by experiencor** [comment]
@prathaprpm You can ignore that cell with ```model.load_weights('weights_coco.h5')```. ```weights_coco.h5``` is the weight file you get after the training. This cell loads this file to continue the training. Since this is the first time you run the code, the weight is not there.

**Comment by prathaprpm** [comment]
thank you
