### ISSUE TITLE
Questions on pretrained weights

### ISSUE THREAD

**Issue by alessandro-montanari** [experiencor/basic-yolo-keras#81]
Hello,
I'd like to know for how many epochs the different feature extractors have been trained on COCO.
And if you know what is the mAP on COCO for these weights. Is the 42.1 on the README about Yolov2?
Thanks!

**Comment by experiencor** [comment]
@alessandro-montanari I stop the training when the validation loss stops improving (3 grace epochs). 

42.1 is the score achieved by the weight released by darknet. 28.6 is the score achieved by my implementation. You may want to refer to https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md for other relative comparisons.

**Comment by alessandro-montanari** [comment]
I see, thanks.
I was wondering if you could share also the weights for the last layer for COCO. I'd like to try the network to detect the classes person and cow and see how it performs with pre-trained weights.
Also, if I want to fine tune for those two classes using my images, is it better to keep the index of the labels the same or it doesn't matter? For example, I think that we you trained on COCO person had index 0 in the list of labels. I am just wondering if somehow the network learns that people are mapped to index 0 and changing the index of the label to fine-tune the last layer would be counterproductive.
Thanks a lot!

**Comment by experiencor** [comment]
@alessandro-montanari I only have the weights to predict 80 classes. Do you still want?

**Comment by alessandro-montanari** [comment]
Yes, that would be nice.

**Comment by experiencor** [comment]
@alessandro-montanari I lost the weights of Full Yolo and Tiny Yolo. Do you want other backends (MobiletNet, Inceptions, ...)?

**Comment by alessandro-montanari** [comment]
Sorry for the delay on this. I don't need the weights anymore.
Thanks!

**Comment by Dhagash4** [comment]
@experiencor I want the multi class weights I am not able to perform multi class detection using the tiny-yolo-raccoon.hr5 
ValueError: Cannot feed value of shape (30,) for Tensor u'Placeholder_41:0', which has shape '(35,)'
This is the error if you have the weights can you please share it with me.
