### ISSUE TITLE
Running on cloud

### ISSUE THREAD

**Issue by bhavindhedhi** [experiencor/basic-yolo-keras#83]
Can you show me how can i train this model on clode like on floydhub or AWS?

**Comment by MassyMeniche** [comment]
Hi @bhavindhedhi  I successfully trained a model on Google Cloud (300$ free trail :) ).
1- I followed the next article to set up Jupyter, https://towardsdatascience.com/running-jupyter-notebook-in-google-cloud-platform-in-15-min-61e16da34d52. 
      a-You can consider installing the latest Anaconda.
      b- Install CUDA and cuDNN 
      c- I installed Tensorflow-gpu 1.3 ( the 1.4 version doesn't work well , some warning about python 3.6 )
2- I had an issue with opencv (cv2.VideoCapture didn't work on ubuntu 16.04) so I got help from here: https://gist.github.com/ksopyla/813a62d6afc4307755e5832a3b62f432

**Comment by bhavindhedhi** [comment]
@MassyMeniche thanks for your reply but can you elaborate more like why have you used jupyter book and how and where do you store dataset like we have four folders for the data alone and what path you put in config.json file 
here-->
`"train": {
        "train_image_folder":   "path to training image folder",
        "train_annot_folder":   "path to training annot folder", }`

**Comment by experiencor** [comment]
@bhavindhedhi You put the data in the EC2 instance and do it like from remote access.
