### ISSUE TITLE
For Prediction

### ISSUE THREAD

**Issue by bhanu223** [experiencor/basic-yolo-keras#84]
I would like to use a pretrained weights file for FullYolo network for prediction purpose. Where can I find that?

**Comment by bhanu223** [comment]
I'm getting an error like this.=:
ValueError: You are trying to load a weight file containing 45 layers into a model with 44 layers.

**Comment by experiencor** [comment]
@bhanu223 What code do you run? I need more information.

**Comment by bhanu223** [comment]
I ran predict.py( FullYolo by using fullyolo weights.).. I tried to load the weights and I got the error

Can You tell me where can I find the pretrained weights for prediction purpose.

**Comment by experiencor** [comment]
@bhanu223 Can you provide the link to the weight file that you downloaded? And the error also.

**Comment by bhanu223** [comment]
I've used the weights from the following link:
https://pjreddie.com/media/files/yolo-voc.weights

Error:You are trying to load a weight file containing 45 layers into a model with 44 layers.

**Comment by bhanu223** [comment]
From where can I download the weights for detecting a Person/Chair in an Image(to be precise)

**Comment by experiencor** [comment]
You use a wrong weight. Please read the readme carefully. Note ```2. Edit the configuration file```.

**Comment by bhanu223** [comment]
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [1.3221, 1.73145, 3.19275, 4.00944, 5.05587, 8.09892, 9.47112, 4.84053, 11.2364, 10.0071],
        "max_box_per_image":    10,        
        "labels":               ["aeroplane","bicycle","bird","boat","bottle","bus","car","cat","chair","cow","diningtable","dog","horse","motorbike","person","pottedplant","sheep","sofa","train","tvmonitor"]
    },

    "train": {
        "train_image_folder":   "",
        "train_annot_folder":   "",     
          
        "train_times":          10,
        "pretrained_weights":   "",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_batches":       250,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "yolo.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}

this is my Config file.


https://github.com/pjreddie/darknet/blob/master/cfg/yolo-voc.cfg

this is the model that I am using for prediction.

**Comment by experiencor** [comment]
@bhanu223 So I see that you trying to run VOC detection using the weights provided by darknet directly. Hmm. My code is not supposed to be used in this way. You can only use https://pjreddie.com/media/files/yolo.weights in the notebook ```Yolo Step-by-Step.ipynb```. It allows you to load the weight from darknet directly.

You can also try the trained Raccoon Detector (instructed in ```2. Edit the configuration file```).

For VOC dataset, you need to train from scratch.

**Comment by Aneesh-c4** [comment]
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 136, in _main_
    debug              = config['train']['debug'])
  File "/home/aneesh/basic-yolo-keras/frontend.py", line 427, in train
    tb_counter  = len([log for log in os.listdir(os.path.expanduser('~/logs/')) if 'yolo' in log]) + 1
OSError: [Errno 2] No such file or directory: '/home/aneesh/logs/'

**Comment by experiencor** [comment]
@Aneesh-c4 The training is saved to '~/logs/' by default (in your case, '/home/aneesh/logs/'). You just need to create that folder to clear the error.

**Comment by Aneesh-c4** [comment]
@experiencor Thanks for the quick reply. I Could train the model by creating logs directory. But the prediction result was not as I expected. I have mailed you the details. Could you please check it.

**Comment by Akashpanchal95** [comment]
I am successfully to build train model on my custom dataset, and it's also good accuracy but one problem is that prediction take long time and when I run on GPU that it better. So Is there any technique to light weight model (faster way to predict on CPU)
