### ISSUE TITLE
Error after first epoch

### ISSUE THREAD

**Issue by prathaprpm** [experiencor/basic-yolo-keras#85]
Hi,
I am getting following error after the 1st epoch while running Yolo Step-by-Step.ipynb
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py in get(self)
    512             while self.is_running():
--> 513                 inputs = self.queue.get(block=True).get()
    514                 if inputs is not None:

C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    607         else:
--> 608             raise self._value
    609 

C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    118         try:
--> 119             result = (True, func(*args, **kwds))
    120         except Exception as e:

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py in get_index(ds, i)
    378     """
--> 379     return ds[i]
    380 

D:\Startup\basic-yolo-keras-master\preprocessing.py in __getitem__(self, idx)
    156             # augment input image and fix object's position and size
--> 157             img, all_objs = self.aug_image(train_instance, jitter=self.jitter)
    158 

D:\Startup\basic-yolo-keras-master\preprocessing.py in aug_image(self, train_instance, jitter)
    237         image = cv2.imread(image_name)
--> 238         h, w, c = image.shape
    239 

AttributeError: 'NoneType' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

StopIteration                             Traceback (most recent call last)
<ipython-input-26-cc95575cd892> in <module>()
     18                     validation_steps = len(valid_batch),
     19                     callbacks        = [early_stop, checkpoint, tensorboard],
---> 20                     max_queue_size   = 3)

C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2044                 batch_index = 0
   2045                 while steps_done < steps_per_epoch:
-> 2046                     generator_output = next(output_generator)
   2047 
   2048                     if not hasattr(generator_output, '__len__'):

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py in get(self)
    516         except Exception as e:
    517             self.stop()
--> 518             raise StopIteration(e)
    519 
    520     def stop(self, timeout=None):

StopIteration: 'NoneType' object has no attribute 'shape'

This error was similar to issue #79 and I have already made the corrections indicated in that issue. still the error persist. Please help

**Comment by experiencor** [comment]
@prathaprpm This error is caused by the wrongly labeled XML files, e.g. the wrong name of the images. You may want to check that.

**Comment by prathaprpm** [comment]
Thank you. The folder address for images was the problem.

**Comment by kashyap-dhriti** [comment]
even after correcting the folder address in the xml annotation files, add '.jpg' in parse_annotation in preprocessing.py, i.e. line number 22
for elem in tree.iter():
            if 'filename' in elem.tag:
                img['filename'] = img_dir + elem.text + '.jpg'
