### ISSUE TITLE
Anchor Dimensions

### ISSUE THREAD

**Issue by dhruvp** [experiencor/basic-yolo-keras#87]
Hi!

First of all thank you for the really well documented work, neat code, and proactivity in taking care of all issues. This is a fantastic repository that's way more practical than most others I've seen.

I had a quick question on anchor dimensions. At the moment, it looks like the anchors are used as follows:

![image](https://user-images.githubusercontent.com/2255690/33960848-e1e5c274-e000-11e7-8fe8-a63e184211ed.png)

I understand that pw, ph correspond to one set of the anchors. I'm targeting bounding boxes of size 20 pixels by 20 pixels. To achieve that, given a grid size of 13 pixels, should my anchors be approximately (20/13 x 20/13) = (1.53, 1.53) ? When I try that in practice the bounding boxes appear way too huge.

In practice anchor sizes of around 0.4 - 0.6 get me the desired dimensions but I don't understand why that is the case as 0.5 * 13 (grid size) = 7.5 and not 20 pixels.

Could you help me understand how to go from a desired bounding box pixel size to an anchor size?

Thanks!

Dhruv

**Comment by experiencor** [comment]
@dhruvp I think you mistake 13 pixels to be the absolute size of each grid cell.

I assume your input image size is 416 x 416. So we divide the image into the grid of size 13x13. There are 169 cells in the grid. The size of each grid cell is (416/13) X (416/13) (not 13 X 13). If you target bounding boxes of size 20 X 20. The size of the anchors should be (20/(416/13)) X (20/(416/13)) = (0.625 X 0625). It explains why this size works better than 1.53 X 1.53.

**Comment by dhruvp** [comment]
Ah that makes a lot of sense. Thank you!
