### ISSUE TITLE
Error at the end of first epoch

### ISSUE THREAD

**Issue by lorenzoferrante** [experiencor/basic-yolo-keras#89]
`Epoch 00001: val_loss improved from inf to 0.29068, saving model to new_weights.h5
Traceback (most recent call last):
  File "/Users/lorenzoferrante/Documents/basic-yolo-keras/train.py", line 140, in <module>
    _main_(args)
  File "/Users/lorenzoferrante/Documents/basic-yolo-keras/train.py", line 136, in _main_
    debug              = config['train']['debug'])
  File "/Users/lorenzoferrante/Documents/basic-yolo-keras/frontend.py", line 446, in train
    max_queue_size   = 8)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/training.py", line 2186, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/callbacks.py", line 415, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 2565, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/models.py", line 147, in save_model
    weight_values = K.batch_get_value(symbolic_weights)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2210, in batch_get_value
    return get_session().run(ops)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1105, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 231, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <type 'NoneType'>`

Can you help me with this please?

**Comment by experiencor** [comment]
@lorenzoferrante Can you let me know your tensorflow and keras versions? I've never seen this error.

**Comment by lorenzoferrante** [comment]
@experiencor of course.
Tensorflow v. 1.4.1
Keras v. 2.1.2

**Comment by lorenzoferrante** [comment]
If it can help, I get the same error running Yolo Step-by-Step.ipynb

`Epoch 1/100
10/11 [==========================>...] - ETA: 1:34 - loss: 3.4850Epoch 00001: val_loss improved from inf to 1.73243, saving model to weights_coco.h5
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-86f0840cbd80> in <module>()
     18                     validation_steps = len(valid_batch),
     19                     callbacks        = [early_stop, checkpoint, tensorboard],
---> 20                     max_queue_size   = 3)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2184                         break
   2185 
-> 2186                 callbacks.on_epoch_end(epoch, epoch_logs)
   2187                 epoch += 1
   2188                 if callback_model.stop_training:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/callbacks.pyc in on_epoch_end(self, epoch, logs)
     71         logs = logs or {}
     72         for callback in self.callbacks:
---> 73             callback.on_epoch_end(epoch, logs)
     74 
     75     def on_batch_begin(self, batch, logs=None):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/callbacks.pyc in on_epoch_end(self, epoch, logs)
    413                             self.model.save_weights(filepath, overwrite=True)
    414                         else:
--> 415                             self.model.save(filepath, overwrite=True)
    416                     else:
    417                         if self.verbose > 0:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.pyc in save(self, filepath, overwrite, include_optimizer)
   2563         """
   2564         from ..models import save_model
-> 2565         save_model(self, filepath, overwrite, include_optimizer)
   2566 
   2567     def save_weights(self, filepath, overwrite=True):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/models.pyc in save_model(model, filepath, overwrite, include_optimizer)
    145                 if symbolic_weights:
    146                     optimizer_weights_group = f.create_group('optimizer_weights')
--> 147                     weight_values = K.batch_get_value(symbolic_weights)
    148                     weight_names = []
    149                     for i, (w, val) in enumerate(zip(symbolic_weights,

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/tensorflow_backend.pyc in batch_get_value(ops)
   2208     """
   2209     if ops:
-> 2210         return get_session().run(ops)
   2211     else:
   2212         return []

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    887     try:
    888       result = self._run(None, fetches, feed_dict, options_ptr,
--> 889                          run_metadata_ptr)
    890       if run_metadata:
    891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1103     # Create a fetch handler to take care of the structure of fetches.
   1104     fetch_handler = _FetchHandler(
-> 1105         self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
   1106 
   1107     # Run request and get response.

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in __init__(self, graph, fetches, feeds, feed_handles)
    412     """
    413     with graph.as_default():
--> 414       self._fetch_mapper = _FetchMapper.for_fetch(fetches)
    415     self._fetches = []
    416     self._targets = []

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in for_fetch(fetch)
    232     elif isinstance(fetch, (list, tuple)):
    233       # NOTE(touts): This is also the code path for namedtuples.
--> 234       return _ListFetchMapper(fetch)
    235     elif isinstance(fetch, dict):
    236       return _DictFetchMapper(fetch)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in __init__(self, fetches)
    339     """
    340     self._fetch_type = type(fetches)
--> 341     self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
    342     self._unique_fetches, self._value_indices = _uniquify_fetches(self._mappers)
    343 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in for_fetch(fetch)
    229     if fetch is None:
    230       raise TypeError('Fetch argument %r has invalid type %r' %
--> 231                       (fetch, type(fetch)))
    232     elif isinstance(fetch, (list, tuple)):
    233       # NOTE(touts): This is also the code path for namedtuples.

TypeError: Fetch argument None has invalid type <type 'NoneType'>`

**Comment by experiencor** [comment]
@lorenzoferrante This is a low level error and I have no idea about it. FYI, my tensorflow is 1.3.0 and keras is 2.0.8.

**Comment by lorenzoferrante** [comment]
To solve the problem I had to delete callbacks (`tensorboard, checkpoint`, but I left `early_stop`) from `self.model.fit_generator` (`frontend.py`), and save the model to json and h5 manually at the end of the epochs.
By the way, thanks for the repo. This is awesome!

**Comment by jashshah** [comment]
@lorenzoferrante Can you outline the steps required to do what you described?

**Comment by SteveIb** [comment]
@lorenzoferrante Thanks for your solution, it works for me. but could you tell me how to save the model manually? i'm alittle bit lost in frontend.py.
