### ISSUE TITLE
Track accuracy during training

### ISSUE THREAD

**Issue by netw0rkf10w** [experiencor/basic-yolo-keras#90]
Hi,
Is it possible to easily track the train/val accuracy during training?
Thanks.

**Comment by experiencor** [comment]
@netw0rkf10w You turn on the ```debug``` flag in the config file to track current recall and average recall.

**Comment by netw0rkf10w** [comment]
@experiencor Sorry I forgot about this issue. Thanks for the answer. I had tried that before but got some error (it did not even start training if I remember correctly). I will check again and get back.
