### ISSUE TITLE
Backend Frontend

### ISSUE THREAD

**Issue by fakhouri-junior** [experiencor/basic-yolo-keras#92]
Hello
I would like to ask you about backend and frontend, it is not quite clear to me what do you mean by them,?
Thanks a lot

**Comment by experiencor** [comment]
@fakhouri-junior Please refer to the YOLO paper https://arxiv.org/abs/1506.02640. The backend is all layers except the last one, which regresses the box sizes and confidence.

**Comment by fakhouri-junior** [comment]
@experiencor Thank you so much for the reply, will go through the paper, I appreciate it
